export const VERIFICATION_EXPORT_VERSION = "2026.09.accounting.1";

const csv = (value: unknown) => `"${String(value ?? "").replaceAll("\"", "\"\"")}"`;
export const tradeExportFields = ["run_id", "strategy_version_id", "sequence", "side", "entry_time", "exit_time", "entry_price", "exit_price", "quantity", "gross_pnl", "net_pnl", "fees", "return_pct", "r_multiple", "mae_pct", "mfe_pct", "holding_ms", "entry_reason", "exit_reason", "details_json", "configuration_hash", "indicator_registry_version", "simulation_engine_version", "metrics_engine_version", "monte_carlo_engine_version", "walk_forward_engine_version", "robustness_engine_version", "stress_engine_version", "export_engine_version", "report_engine_version", "random_seed"] as const;
export const tradeCsvHeader = () => `${tradeExportFields.join(",")}\n`;
export type TradeExportMetadata = { configurationHash?: string; indicatorRegistryVersion?: string; engineVersion?: string; metricsVersion?: string; monteCarloEngineVersion?: string | null; walkForwardEngineVersion?: string | null; robustnessEngineVersion?: string | null; stressEngineVersion?: string | null; exportVersion?: string | null; reportEngineVersion?: string | null; randomSeed?: number };
export const tradeCsvLine = (runId: string, strategyVersionId: string, row: Record<string, unknown>, metadata: TradeExportMetadata = {}) => {
  const values: Record<string, unknown> = { run_id: runId, strategy_version_id: strategyVersionId, configuration_hash: metadata.configurationHash, indicator_registry_version: metadata.indicatorRegistryVersion, simulation_engine_version: metadata.engineVersion, metrics_engine_version: metadata.metricsVersion, monte_carlo_engine_version: metadata.monteCarloEngineVersion, walk_forward_engine_version: metadata.walkForwardEngineVersion, robustness_engine_version: metadata.robustnessEngineVersion, stress_engine_version: metadata.stressEngineVersion, export_engine_version: metadata.exportVersion, report_engine_version: metadata.reportEngineVersion, random_seed: metadata.randomSeed, ...row };
  return `${tradeExportFields.map((field) => csv(values[field])).join(",")}\n`;
};
