import type { SimTrade } from "./simulation.js";

export const FEE_AUDIT_TOLERANCE = 1e-6;
type FeeType = "MAKER" | "TAKER";
type FeeConfig = { makerFeePct: number; takerFeePct: number };
const median = (values: number[]) => { const ordered = [...values].sort((a, b) => a - b), middle = Math.floor(ordered.length / 2); return ordered.length % 2 ? ordered[middle] ?? 0 : ((ordered[middle - 1] ?? 0) + (ordered[middle] ?? 0)) / 2; };
const feeRate = (details: Record<string, unknown>, leg: "entry" | "exit", costs: FeeConfig) => { const explicit = Number(details[`${leg}FeeRatePct`]); if (Number.isFinite(explicit)) return explicit / 100; const type = String(details[`${leg}FeeType`] ?? "TAKER") as FeeType; return (type === "MAKER" ? costs.makerFeePct : costs.takerFeePct) / 100; };

export function auditTradeFees(trades: SimTrade[], costs: FeeConfig) {
  const rows = trades.map((trade, index) => {
    const details = trade.details, quantity = Math.abs(Number(trade.quantity)), entryFillPrice = Math.abs(Number(trade.entryPrice)), exitFillPrice = Math.abs(Number(trade.exitPrice));
    const entryNotional = entryFillPrice * quantity, exitNotional = exitFillPrice * quantity, entryRate = feeRate(details, "entry", costs), exitRate = feeRate(details, "exit", costs), expectedEntryFee = entryNotional * entryRate, expectedExitFee = exitNotional * exitRate, expectedTotalFee = expectedEntryFee + expectedExitFee, persistedEntryFee = Number(details.entryFee), persistedExitFee = Number(details.exitFee), persistedTotalFee = Number(trade.fees), difference = persistedTotalFee - expectedTotalFee;
    return { sequence: index + 1, persistedEntryFee, persistedExitFee, persistedTotalFee, reconstructedEntryFee: expectedEntryFee, reconstructedExitFee: expectedExitFee, reconstructedTotalFee: expectedTotalFee, entryNotional, exitNotional, entryRate, exitRate, difference, tolerance: FEE_AUDIT_TOLERANCE, status: !Number.isFinite(persistedEntryFee) || !Number.isFinite(persistedExitFee) ? "NOT_RECONSTRUCTABLE" : Math.abs(difference) <= FEE_AUDIT_TOLERANCE ? "PASS" : "FAIL" };
  });
  const entryFees = rows.map((row) => row.persistedEntryFee), exitFees = rows.map((row) => row.persistedExitFee), totalFees = rows.reduce((sum, row) => sum + row.persistedTotalFee, 0), totalEntryFees = entryFees.reduce((sum, value) => sum + value, 0), totalExitFees = exitFees.reduce((sum, value) => sum + value, 0), totalEntryNotional = rows.reduce((sum, row) => sum + row.entryNotional, 0), totalExitNotional = rows.reduce((sum, row) => sum + row.exitNotional, 0), totalTurnover = totalEntryNotional + totalExitNotional, reconstructedFees = rows.reduce((sum, row) => sum + row.reconstructedTotalFee, 0), statuses = rows.map((row) => row.status), status = statuses.some((value) => value === "NOT_RECONSTRUCTABLE") ? "NOT_RECONSTRUCTABLE" : statuses.some((value) => value === "FAIL") ? "FAIL" : rows.some((row) => Math.abs(row.difference) > FEE_AUDIT_TOLERANCE / 10) ? "WARNING" : "PASS";
  return { check: "EXPECTED_FEE_RECONCILIATION", status, tolerance: FEE_AUDIT_TOLERANCE, tradeCount: trades.length, totalEntryFees, totalExitFees, totalFees, reconstructedFees, feeDifference: totalFees - reconstructedFees, averageFeePerTrade: trades.length ? totalFees / trades.length : 0, medianFeePerTrade: median(rows.map((row) => row.persistedTotalFee)), totalEntryNotional, totalExitNotional, totalTurnover, effectiveFeeRate: totalTurnover ? totalFees / totalTurnover : 0, feesPctInitialBalance: null, feesPctGrossTradingPnl: null, makerFees: rows.reduce((sum, row) => sum + (String((trades[row.sequence - 1]?.details ?? {}).entryFeeType ?? "TAKER") === "MAKER" ? row.persistedEntryFee : 0) + (String((trades[row.sequence - 1]?.details ?? {}).exitFeeType ?? "TAKER") === "MAKER" ? row.persistedExitFee : 0), 0), takerFees: rows.reduce((sum, row) => sum + (String((trades[row.sequence - 1]?.details ?? {}).entryFeeType ?? "TAKER") === "TAKER" ? row.persistedEntryFee : 0) + (String((trades[row.sequence - 1]?.details ?? {}).exitFeeType ?? "TAKER") === "TAKER" ? row.persistedExitFee : 0), 0), rows };
}
