import type { SimTrade } from "./simulation.js";

export const METRICS_ENGINE_VERSION = "2026.09.accounting.1";
const mean = (values: number[]) => values.length ? values.reduce((a, b) => a + b, 0) / values.length : 0;
const std = (values: number[]) => values.length ? Math.sqrt(mean(values.map((x) => (x - mean(values)) ** 2))) : 0;
const median = (values: number[]) => { if (!values.length) return 0; const ordered = [...values].sort((a, b) => a - b), middle = Math.floor(ordered.length / 2); return ordered.length % 2 ? ordered[middle] : (ordered[middle - 1] + ordered[middle]) / 2; };
function streaks(pnl: number[]) { let wins = 0, losses = 0, maxWins = 0, maxLosses = 0; for (const value of pnl) { if (value > 0) { wins++; losses = 0; maxWins = Math.max(maxWins, wins); } else if (value < 0) { losses++; wins = 0; maxLosses = Math.max(maxLosses, losses); } } return { maxConsecutiveWins: maxWins, maxConsecutiveLosses: maxLosses }; }
const detailNumber = (trade: SimTrade, key: string) => key === "funding" && trade.details.fundingPnl != null ? Number(trade.details.fundingPnl) : Number(trade.details[key] ?? 0);
function worstPeriod(trades: SimTrade[], period: "day" | "week" | "month") { const totals = new Map<string, number>(); for (const trade of trades) { const date = new Date(trade.exitTime); const key = period === "month" ? `${date.getUTCFullYear()}-${String(date.getUTCMonth() + 1).padStart(2, "0")}` : period === "day" ? date.toISOString().slice(0, 10) : (() => { const monday = new Date(Date.UTC(date.getUTCFullYear(), date.getUTCMonth(), date.getUTCDate())); monday.setUTCDate(monday.getUTCDate() - ((monday.getUTCDay() + 6) % 7)); return monday.toISOString().slice(0, 10); })(); totals.set(key, (totals.get(key) ?? 0) + Number(trade.netPnl)); } const worst = [...totals.entries()].sort((a, b) => a[1] - b[1])[0]; return worst ? { period: worst[0], netProfit: worst[1] } : null; }
export function verificationMetrics(trades: SimTrade[], equity: Array<{ time: number; balance: number }>) {
  const pnl = trades.map((t) => Number(t.netPnl)), wins = pnl.filter((x) => x > 0), losses = pnl.filter((x) => x < 0), returns = trades.map((t) => t.returnPct / 100);
  let peak = equity[0]?.balance ?? 0, maxDrawdown = 0, maxDrawdownPct = 0, start = peak, durationStart = equity[0]?.time ?? 0, longestDuration = 0; const underwater = equity.map((p) => { if (p.balance >= peak) { peak = p.balance; start = peak; durationStart = p.time; } const drawdown = p.balance - peak, pct = peak ? drawdown / peak : 0; maxDrawdown = Math.min(maxDrawdown, drawdown); maxDrawdownPct = Math.min(maxDrawdownPct, pct); if (p.balance < peak) longestDuration = Math.max(longestDuration, p.time - durationStart); return { ...p, drawdown, drawdownPct: pct }; });
  const grossProfit = wins.reduce((a, b) => a + b, 0), grossLoss = Math.abs(losses.reduce((a, b) => a + b, 0)), averageReturn = mean(returns), returnDeviation = std(returns), downsideDeviation = Math.sqrt(mean(returns.filter((value) => value < 0).map((value) => value ** 2))), sharpe = returnDeviation ? averageReturn / returnDeviation * Math.sqrt(365) : null, sortino = downsideDeviation ? averageReturn / downsideDeviation * Math.sqrt(365) : null, omega = grossLoss ? grossProfit / grossLoss : null;
  const averageWin = mean(wins), averageLoss = mean(losses), first = equity[0]?.balance ?? 0, last = equity.at(-1)?.balance ?? first, elapsedDays = Math.max(0, ((equity.at(-1)?.time ?? 0) - (equity[0]?.time ?? 0)) / 86_400_000), annualizedReturnPct = first > 0 && elapsedDays > 0 ? (Math.pow(Math.max(0, last) / first, 365 / elapsedDays) - 1) * 100 : null, calmar = annualizedReturnPct != null && maxDrawdownPct < 0 ? annualizedReturnPct / Math.abs(maxDrawdownPct * 100) : null, ulcerIndex = Math.sqrt(mean(underwater.map((point) => point.drawdownPct ** 2))) * 100, holding = trades.map((trade) => trade.holdingMs), orderedEntries = [...trades].sort((a, b) => a.entryTime - b.entryTime), gaps = orderedEntries.slice(1).map((trade, index) => trade.entryTime - orderedEntries[index].entryTime), totalFees = trades.reduce((sum, trade) => sum + Number(trade.fees), 0), totalFunding = trades.reduce((sum, trade) => sum + detailNumber(trade, "funding"), 0), totalSlippageImpact = trades.reduce((sum, trade) => sum + detailNumber(trade, "slippageImpact"), 0), timeInMarketMs = holding.reduce((sum, value) => sum + value, 0), totalPeriodMs = Math.max(0, (equity.at(-1)?.time ?? 0) - (equity[0]?.time ?? 0)), recoveryFactor = maxDrawdown ? (last - first) / Math.abs(maxDrawdown) : null, winsCount = wins.length, lossesCount = losses.length, breakEvenTrades = pnl.filter((value) => value === 0).length, riskOfRuinPct = averageReturn <= 0 || averageLoss >= 0 ? 100 : Math.min(100, Math.pow(Math.max(0, Math.abs(averageLoss) / Math.max(averageWin || 0.0000001, .0000001)) * (lossesCount / Math.max(1, winsCount)), Math.max(1, first / Math.abs(averageLoss || -1))) * 100), longTrades = trades.filter((trade) => trade.side === "LONG"), shortTrades = trades.filter((trade) => trade.side === "SHORT");
  const grossPnl = trades.reduce((sum, trade) => sum + Number(trade.grossPnl), 0), netPnl = pnl.reduce((sum, value) => sum + value, 0), grossTradingProfit = trades.reduce((sum, trade) => Math.max(0, Number(trade.grossPnl)) + sum, 0), grossTradingLoss = trades.reduce((sum, trade) => Math.min(0, Number(trade.grossPnl)) + sum, 0), balanceReconciliationDifference = last - first - netPnl;
  return { tradeCount: trades.length, netProfit: netPnl, netProfitPct: first ? netPnl / first * 100 : 0, grossPnl, grossTradingPnl: grossPnl, grossTradingProfit, grossTradingLoss, netWinningPnl: grossProfit, netLosingPnl: -grossLoss, balanceReconciliationDifference, grossProfit, grossLoss, totalFees, totalFunding, totalSlippageImpact, timeInMarketMs, timeInMarketPct: totalPeriodMs ? timeInMarketMs / totalPeriodMs * 100 : 0, annualizedReturnPct, cagrPct: annualizedReturnPct, profitFactor: grossLoss ? grossProfit / grossLoss : null, gainToPainRatio: grossLoss ? grossProfit / grossLoss : null, recoveryFactor, winRate: trades.length ? wins.length / trades.length * 100 : 0, winningTrades: winsCount, losingTrades: lossesCount, breakEvenTrades, averageTrade: mean(pnl), medianTrade: median(pnl), largestWinningTrade: wins.length ? Math.max(...wins) : 0, largestLosingTrade: losses.length ? Math.min(...losses) : 0, averageWin: mean(wins), averageLoss: mean(losses), expectancy: mean(pnl), payoffRatio: Math.abs(mean(losses)) ? mean(wins) / Math.abs(mean(losses)) : null, maxDrawdown, maxDrawdownPct: maxDrawdownPct * 100, averageDrawdownPct: mean(underwater.filter((point) => point.drawdownPct < 0).map((point) => point.drawdownPct)) * 100, longestUnderwaterMs: longestDuration, worstDay: worstPeriod(trades, "day"), worstWeek: worstPeriod(trades, "week"), worstMonth: worstPeriod(trades, "month"), modeledLiquidations: 0, minimumDistanceToLiquidationPct: null, riskOfRuinPct, sharpe, sortino, calmar, omega, ulcerIndex, averageHoldingMs: mean(holding), medianHoldingMs: median(holding), minHoldingMs: holding.length ? Math.min(...holding) : 0, maxHoldingMs: holding.length ? Math.max(...holding) : 0, winningAverageHoldingMs: mean(trades.filter((trade) => Number(trade.netPnl) > 0).map((trade) => trade.holdingMs)), losingAverageHoldingMs: mean(trades.filter((trade) => Number(trade.netPnl) < 0).map((trade) => trade.holdingMs)), holdingDistribution: { under1h: holding.filter((value) => value < 3_600_000).length, oneToFourHours: holding.filter((value) => value >= 3_600_000 && value < 14_400_000).length, fourTo24Hours: holding.filter((value) => value >= 14_400_000 && value < 86_400_000).length, over24Hours: holding.filter((value) => value >= 86_400_000).length }, averageTimeBetweenTradesMs: mean(gaps), averageMaePct: mean(trades.map((trade) => trade.maePct)), averageMfePct: mean(trades.map((trade) => trade.mfePct)), ...streaks(pnl), long: { ...summarize(longTrades), percentage: trades.length ? longTrades.length / trades.length * 100 : 0 }, short: { ...summarize(shortTrades), percentage: trades.length ? shortTrades.length / trades.length * 100 : 0 }, equityFinal: last, underwater };
}
function summarize(trades: SimTrade[]) { const pnl = trades.map((x) => Number(x.netPnl)); return { count: trades.length, percentage: 0, netProfit: pnl.reduce((a, b) => a + b, 0), winRate: trades.length ? pnl.filter((x) => x > 0).length / trades.length * 100 : 0, expectancy: mean(pnl) }; }
export function calendarBreakdown(trades: SimTrade[]) { const items: Record<string, { trades: number; pnl: number; wins: number }> = {}; for (const t of trades) { const date = new Date(t.entryTime), key = `${date.getUTCFullYear()}-${String(date.getUTCMonth() + 1).padStart(2, "0")}`; const item = items[key] ??= { trades: 0, pnl: 0, wins: 0 }; item.trades++; item.pnl += Number(t.netPnl); item.wins += Number(t.netPnl) > 0 ? 1 : 0; } return items; }
export function scorecard(metrics: ReturnType<typeof verificationMetrics>, warnings: string[]) { const checks = [{ name: "Positive expectancy", passed: metrics.expectancy > 0 }, { name: "Profit factor ≥ 1.2", passed: (metrics.profitFactor ?? 0) >= 1.2 }, { name: "Max drawdown ≤ 20%", passed: Math.abs(metrics.maxDrawdownPct) <= 20 }, { name: "At least 30 trades", passed: metrics.tradeCount >= 30 }, { name: "Funding modeled", passed: !warnings.includes("Funding was not modeled.") }]; const passed = checks.filter((x) => x.passed).length; return { score: Math.round(passed / checks.length * 100), status: passed >= 4 ? "PASS" : passed >= 3 ? "WARNING" : "FAIL", checks }; }
