import PDFDocument from "pdfkit";
import { equityChartDomain } from "./chart-domain.js";

type Row = Record<string, unknown>;
const clean = (value: unknown) => String(value ?? "-").replace(/[^\x20-\x7E]/g, "?");
const number = (value: unknown, digits = 2) => Number(value ?? 0).toLocaleString("en-US", { maximumFractionDigits: digits });
const date = (value: unknown) => {
  if (!value) return "-";
  const numeric = Number(value);
  const parsed = new Date(Number.isFinite(numeric) && numeric > 1_000_000_000 ? numeric : String(value));
  return Number.isNaN(parsed.getTime()) ? clean(value) : parsed.toISOString().replace("T", " ").replace(/\.\d{3}Z$/, " UTC");
};

export async function verificationReportPdf(input: { run: Row; version: Row | null; result: Row; trades: Row[]; logs: Row[]; audit?: Row }) {
  return await new Promise<Buffer>((resolve, reject) => {
    const document = new PDFDocument({ size: "A4", margin: 40, info: { Title: `Treidin verification ${clean(input.run.name)}`, Author: "Treidin" } });
    const chunks: Buffer[] = []; document.on("data", (chunk: Buffer) => chunks.push(chunk)); document.on("end", () => resolve(Buffer.concat(chunks))); document.on("error", reject);
    let page = 1;
    const header = () => { document.rect(0, 0, 595, 54).fill("#07111e"); document.fillColor("#2dd4bf").font("Helvetica-Bold").fontSize(13).text("TREIDIN - STRATEGY VERIFICATION REPORT", 40, 20); document.fillColor("#9fb0c2").font("Helvetica").fontSize(8).text(`Generated ${new Date().toISOString().replace("T", " ").slice(0, 19)} UTC`, 390, 23, { width: 165, align: "right" }); document.x = 40; document.y = 72; };
    const footer = () => { document.fillColor("#718096").font("Helvetica").fontSize(8).text(`Treidin local verification - page ${page}`, 40, 790, { width: 515, align: "center" }); };
    const nextPage = () => { footer(); document.addPage(); page++; header(); };
    const requireSpace = (height: number) => { if (document.y + height > 780) nextPage(); };
    const title = (text: string) => { requireSpace(28); document.moveTo(40, document.y).lineTo(555, document.y).strokeColor("#cbd5e1").lineWidth(.5).stroke(); document.moveDown(.55).fillColor("#0f5f9e").font("Helvetica-Bold").fontSize(12).text(clean(text)); document.moveDown(.35); };
    const fields = (items: Array<[string, unknown]>) => { for (const [label, value] of items) { requireSpace(17); const y = document.y; document.fillColor("#64748b").font("Helvetica-Bold").fontSize(8).text(clean(label).toUpperCase(), 40, y, { width: 185 }); document.fillColor("#1f2937").rect(225, y - 3, 330, 14).fill(); document.fillColor("#e2e8f0").font("Helvetica").fontSize(8).text(clean(value), 231, y, { width: 318 }); document.y = y + 17; } document.moveDown(.45); };
    const table = (headers: string[], rows: unknown[][], widths: number[]) => { const drawHeader = () => { requireSpace(24); const y = document.y; document.rect(40, y - 3, 515, 17).fill("#0f2742"); let x = 44; headers.forEach((item, index) => { document.fillColor("#cbd5e1").font("Helvetica-Bold").fontSize(7).text(clean(item), x, y + 2, { width: widths[index] - 5, ellipsis: true }); x += widths[index]; }); document.y = y + 19; };
      drawHeader(); rows.forEach((row) => { requireSpace(15); if (document.y + 15 > 780) { nextPage(); drawHeader(); } const y = document.y; let x = 44; row.forEach((item, index) => { document.fillColor("#28394c").font("Helvetica").fontSize(7).text(clean(item), x, y, { width: widths[index] - 5, ellipsis: true }); x += widths[index]; }); document.strokeColor("#d9e2ec").opacity(.2).moveTo(40, y + 12).lineTo(555, y + 12).stroke().opacity(1); document.y = y + 14; }); document.moveDown(.5); };
    const chart = (label: string, series: Array<{ values: number[]; color: string; width?: number }>) => { const usable = series.filter((line) => line.values.length > 1 && line.values.some(Number.isFinite)); if (!usable.length) return; requireSpace(205); const top = document.y, left = 40, width = 515, height = 145, values = usable.flatMap((line) => line.values).filter(Number.isFinite), domain = equityChartDomain(values), min = domain.min, max = domain.max, longest = Math.max(...usable.map((line) => line.values.length)), x = (index: number, length: number) => left + index / Math.max(length - 1, 1) * width, y = (value: number) => top + 20 + height - (value - min) / Math.max(max - min, 1) * height; document.fillColor("#64748b").font("Helvetica-Bold").fontSize(8).text(clean(label).toUpperCase(), left, top); document.rect(left, top + 20, width, height).fill("#f8fafc"); document.strokeColor("#cbd5e1").lineWidth(.5).rect(left, top + 20, width, height).stroke(); [0, .5, 1].forEach((ratio) => { const lineY = top + 20 + height * ratio; document.strokeColor("#dbe5ef").moveTo(left, lineY).lineTo(left + width, lineY).stroke(); }); usable.forEach((line) => { document.strokeColor(line.color).lineWidth(line.width ?? 1.3).opacity(.9).moveTo(x(0, line.values.length), y(line.values[0])); line.values.slice(1).forEach((value, index) => document.lineTo(x(index + 1, line.values.length), y(value))); document.stroke().opacity(1); }); document.fillColor("#64748b").font("Helvetica").fontSize(7).text(number(max), left, top + 18, { width: 65 }).text(number(min), left, top + 20 + height - 4, { width: 65 }); document.fillColor("#64748b").text(`0                                                       ${longest - 1} samples`, left, top + 171, { width, align: "center" }); document.y = top + 190; };
    header();
    const result = input.result, metrics = (result.metrics ?? {}) as Row, breakdowns = (result.breakdowns ?? {}) as Row, funnel = (result.funnel ?? {}) as Row, scorecard = (result.scorecard ?? {}) as Row, audit = (input.audit ?? {}) as Row, feeAudit = (audit.feeAudit ?? metrics.feeAudit ?? {}) as Row, feeRates = (feeAudit.rateConversions ?? {}) as Row, auditTradeCounts = (audit.tradeCounts ?? {}) as Row, auditAccounting = (audit.accounting ?? {}) as Row, auditReconciliation = Array.isArray(audit.reconciliation) ? audit.reconciliation as Row[] : [];
    document.fillColor("#0f172a").font("Helvetica-Bold").fontSize(20).text(clean(input.run.name)); document.fillColor("#64748b").font("Helvetica").fontSize(9).text("Complete, reproducible historical strategy test", { continued: false }); document.moveDown(.8);
    title("Run identity"); fields([["Run ID", input.run.id], ["Strategy version", input.run.strategyVersionId], ["Symbol / profile", `${input.run.symbol} / ${input.run.profile}`], ["Requested range", `${date(input.run.requestedStart)} to ${date(input.run.requestedEnd)}`], ["Configuration hash", input.run.configurationHash], ["Random seed", input.run.randomSeed]]);
    title("Core performance"); fields([["Net profit", `${number(metrics.netProfit)} (${number(metrics.netProfitPct)}%)`], ["Final equity", number(metrics.equityFinal)], ["Trade count", metrics.tradeCount], ["Profit factor", number(metrics.profitFactor, 3)], ["Win rate", `${number(metrics.winRate, 1)}%`], ["Maximum drawdown", `${number(metrics.maxDrawdown)} (${number(metrics.maxDrawdownPct)}%)`], ["Sharpe / Sortino", `${number(metrics.sharpe, 3)} / ${number(metrics.sortino, 3)}`], ["Scorecard", `${scorecard.status ?? "-"} (${scorecard.score ?? "-"})`]]);
    const equityCurve = Array.isArray(result.equityCurve) ? result.equityCurve as Row[] : [];
    title("Equity curve"); chart("Historical account equity", [{ values: equityCurve.map((point) => Number(point.balance)).filter(Number.isFinite), color: "#0f766e", width: 1.6 }]);
    title("Strategy configuration"); fields([["Trigger / execution timeframe", `${(input.version?.configuration as Row | undefined)?.triggerTimeframe ?? "-"} / ${(input.version?.configuration as Row | undefined)?.executionTimeframe ?? "-"}`], ["Directions", (input.version?.configuration as Row | undefined)?.directions], ["Stop / target", `${((input.version?.configuration as Row | undefined)?.stop as Row | undefined)?.type ?? "-"} / ${((input.version?.configuration as Row | undefined)?.takeProfit as Row | undefined)?.type ?? "-"}`], ["Registry version", input.version?.indicatorRegistryVersion]]);
    title("Risk, execution and exposure"); table(["Metric", "Value", "Metric", "Value"], [["Gross trading P&L", number(metrics.grossTradingPnl), "Gross winning trades", number(metrics.grossWinningTradesProfit)], ["Gross losing trades", number(metrics.grossLosingTradesLoss), "Net profit", number(metrics.netProfit)], ["Net winning trades", number(metrics.netWinningTradesProfit), "Net losing trades", number(metrics.netLosingTradesLoss)], ["Funding", number(metrics.totalFunding), "Time in market", `${number(metrics.timeInMarketPct)}%`], ["Risk of ruin", `${number(metrics.riskOfRuinPct)}%`, "Annualized return", `${number(metrics.annualizedReturnPct)}%`], ["Intrabar ambiguous trades", funnel.ambiguousFills ?? "-", "Ambiguity rate", funnel.ambiguousFills == null || !metrics.tradeCount ? "-" : `${number(Number(funnel.ambiguousFills) / Number(metrics.tradeCount) * 100, 2)}%`], ["Resolution", `${funnel.conservativeResolutions ?? 0} conservative / ${funnel.favorableResolutions ?? 0} favorable`, "Execution timeframe", (input.version?.configuration as Row | undefined)?.executionTimeframe ?? "-"]], [130, 128, 130, 127]);
    title("Fee audit and turnover"); table(["Metric", "Value", "Metric", "Value"], [["Audit check", feeAudit.check, "Status", feeAudit.status], ["Entry fees", number(feeAudit.totalEntryFees), "Exit fees", number(feeAudit.totalExitFees)], ["Total fees", number(feeAudit.totalFees), "Reconstructed fees", number(feeAudit.reconstructedFees)], ["Fee difference", number(feeAudit.feeDifference, 8), "Average / median fee", `${number(feeAudit.averageFeePerTrade, 4)} / ${number(feeAudit.medianFeePerTrade, 4)}`], ["Maker fees", number(feeAudit.makerFees), "Taker fees", number(feeAudit.takerFees)], ["Maker / taker rates", `${number(feeRates.makerFeePct, 4)}% / ${number(feeRates.takerFeePct, 4)}%`, "Applied decimals", `${number(feeRates.makerRateDecimal, 6)} / ${number(feeRates.takerRateDecimal, 6)}`], ["Entry notional", number(feeAudit.totalEntryNotional), "Exit notional", number(feeAudit.totalExitNotional)], ["Turnover", number(feeAudit.totalTurnover), "Effective fee rate", `${number(Number(feeAudit.effectiveFeeRate) * 100, 4)}%`], ["Fees / initial balance", `${number(feeAudit.feesPctInitialBalance)}%`, "Fees / gross trading P&L", `${number(feeAudit.feesPctGrossTradingPnl)}%`], ["Fees per year", number(feeAudit.feesPerYear), "Fees per 100 trades", number(feeAudit.feesPer100Trades)]], [130, 128, 130, 127]);
    const mc = breakdowns.monteCarlo as Row | null, oos = (breakdowns.outOfSample ?? {}) as Row, dataAudit = (breakdowns.dataAudit ?? {}) as Row;
    title("Out-of-sample and Monte Carlo"); fields([["OOS period", `${date(oos.start)} to ${date(oos.end)}`], ["OOS net profit / PF", `${number(oos.netProfit)} / ${number(oos.profitFactor, 3)}`], ["Monte Carlo simulations", mc?.count ?? "Not run"], ["Monte Carlo model", mc?.model ?? "-"], ["Monte Carlo final equity P5 / median / P95", mc ? `${number(mc.p05FinalEquity)} / ${number(mc.medianFinalEquity)} / ${number(mc.p95FinalEquity)}` : "-"], ["Monte Carlo probability of profit", mc ? `${number(mc.probabilityOfProfit, 1)}%` : "-"], ["Ruined paths / percentage", mc ? `${mc.ruinedPathCount ?? 0} / ${number(mc.ruinProbabilityPct, 2)}%` : "-"], ["Earliest / median ruin trade", mc ? `${mc.earliestRuinTradeIndex ?? "-"} / ${mc.medianRuinTradeIndex ?? "-"}` : "-"], ["Minimum simulated equity / drawdown", mc ? `${number(mc.minimumSimulatedEquity)} / ${number(mc.minimumSimulatedDrawdownPct)}%` : "-"]]);
    const percentilePaths = (mc?.percentilePaths ?? {}) as Row, monteCarloPaths = Array.isArray(mc?.paths) ? mc.paths as number[][] : [];
    if (monteCarloPaths.length || Array.isArray(percentilePaths.median)) { title("Monte Carlo equity paths"); chart("Simulated paths with P5 / median / P95", [...monteCarloPaths.slice(0, 120).map((values) => ({ values, color: "#b8c7d9", width: .25 })), { values: Array.isArray(percentilePaths.p05) ? percentilePaths.p05 as number[] : [], color: "#dc2626", width: 1.2 }, { values: Array.isArray(percentilePaths.median) ? percentilePaths.median as number[] : [], color: "#0f766e", width: 1.7 }, { values: Array.isArray(percentilePaths.p95) ? percentilePaths.p95 as number[] : [], color: "#2563eb", width: 1.2 }]); }
    const stressPaths = Array.isArray(breakdowns.costStress) ? (breakdowns.costStress as Row[]).map((row) => ({ values: Array.isArray(row.equityCurve) ? (row.equityCurve as Row[]).map((point) => Number(point.balance)) : [], color: row.name === "SEVERE_FRICTION" ? "#dc2626" : "#f59e0b", width: 1.2 })) : []; if (stressPaths.some((line) => line.values.length > 1)) { title("Stress equity paths"); chart("Cost and execution stress equity", stressPaths); }
    title("Scorecard and robustness"); table(["Check", "Status"], Array.isArray(scorecard.checks) ? (scorecard.checks as Row[]).map((check) => [check.name, check.passed ? "PASS" : "FAIL"]) : [], [350, 165]); table(["Scenario", "Trades", "Net profit", "Profit factor", "Max drawdown %"], Array.isArray(breakdowns.costStress) ? (breakdowns.costStress as Row[]).map((row) => [row.name, row.trades, number(row.netProfit), number(row.profitFactor, 3), number(row.maxDrawdownPct)]) : [], [145, 70, 105, 100, 95]);
    title("Data quality and bias audit"); fields([["Closed / complete candles only", dataAudit.usesClosedCompleteCandlesOnly ? "PASS" : "FAIL"], ["Point-in-time feature access", dataAudit.pointInTimeFeatureAccess ? "PASS" : "FAIL"], ["Strategy warm-up complete", dataAudit.strategyWarmupComplete ? "PASS" : "FAIL"], ["Breakdown warm-up complete", dataAudit.breakdownWarmupComplete ? "PASS" : "WARNING - REGIME_CLASSIFICATION_UNAVAILABLE"], ["Trigger / execution timeframe", `${dataAudit.triggerTimeframe ?? "-"} / ${dataAudit.executionTimeframe ?? "-"}`], ["Exchange rules applied", dataAudit.exchangeRulesApplied ? "YES" : "NO"], ["Required timeframes", Array.isArray(dataAudit.requiredTimeframes) ? dataAudit.requiredTimeframes.join(", ") : "-"], ["Data fingerprint", (dataAudit.fingerprint as Row | undefined)?.checksum ?? "-"], ["Known limitations", Array.isArray(dataAudit.knownLimitations) && dataAudit.knownLimitations.length ? dataAudit.knownLimitations.join("; ") : "None reported"]]);
    const reconciliation = (metric: string) => auditReconciliation.find((item) => item.metric === metric);
    title("Audit & Consistency"); fields([["Audit status", audit.status ?? "NOT_RECONSTRUCTABLE"], ["Audit timestamp", date(audit.auditTimestamp)], ["Recommended action", audit.recommendedAction ?? "-"], ["Persisted / reconstructed / exportable trades", `${auditTradeCounts.persisted ?? "-"} / ${reconciliation("tradeCount")?.reconstructedValue ?? "-"} / ${auditTradeCounts.exportable ?? input.trades.length}`], ["Persisted / reconstructed net P&L", `${number(reconciliation("netProfit")?.persistedValue)} / ${number(reconciliation("netProfit")?.reconstructedValue)}`], ["P&L difference", number(reconciliation("netProfit")?.difference, 8)], ["Persisted / reconstructed final balance", `${number(reconciliation("equityFinal")?.persistedValue)} / ${number(reconciliation("equityFinal")?.reconstructedValue)}`], ["Balance difference", number(reconciliation("equityFinal")?.difference, 8)], ["Persisted / reconstructed fees", `${number(reconciliation("totalFees")?.persistedValue)} / ${number(reconciliation("totalFees")?.reconstructedValue)}`], ["Fee difference", number(reconciliation("totalFees")?.difference, 8)], ["Persisted / reconstructed funding", `${number(reconciliation("totalFunding")?.persistedValue)} / ${number(reconciliation("totalFunding")?.reconstructedValue)}`], ["Funding difference", number(reconciliation("totalFunding")?.difference, 8)], ["Slippage model / reconciliation", `${auditAccounting.slippageModel ?? "-"} / ${reconciliation("totalSlippageImpact")?.status ?? "NOT_RECONSTRUCTABLE"}`], ["Sequence integrity", auditTradeCounts.invalidOrder || auditTradeCounts.duplicateSequence ? "FAIL" : "PASS"], ["Duplicate trade IDs / numbers", `${auditTradeCounts.duplicateTradeIds ?? 0} / ${auditTradeCounts.duplicateSequence ? 1 : 0}`], ["Missing provenance", Array.isArray(audit.missingFields) && audit.missingFields.length ? audit.missingFields.join(", ") : "None"]]); table(["Audit check", "Status"], Object.entries((audit.checks ?? {}) as Row).map(([check, status]) => [check, status]), [350, 165]);
    title("Reproducibility & Engine Versions"); fields([["Strategy configuration hash", input.run.configurationHash], ["Indicator registry version", input.version?.indicatorRegistryVersion], ["Simulation engine", input.run.engineVersion], ["Metrics engine", input.run.metricsVersion], ["Monte Carlo engine", input.run.monteCarloEngineVersion], ["Walk-forward engine", input.run.walkForwardEngineVersion ?? "LEGACY_UNVERSIONED"], ["Robustness engine", input.run.robustnessEngineVersion ?? "LEGACY_UNVERSIONED"], ["Stress engine", input.run.stressEngineVersion ?? "LEGACY_UNVERSIONED"], ["Export engine", input.run.exportVersion], ["Report engine", input.run.reportEngineVersion ?? "LEGACY_UNVERSIONED"], ["Random seed", input.run.randomSeed], ["Data fingerprint", (dataAudit.fingerprint as Row | undefined)?.checksum ?? "-"]]);
    title("Market regimes and walk-forward"); table(["Regime", "Trades", "Net profit", "Win rate %"], Array.isArray(breakdowns.marketRegimes) ? (breakdowns.marketRegimes as Row[]).map((row) => [row.regime, row.trades, number(row.netProfit), number(row.winRate, 1)]) : [], [170, 95, 130, 120]); const walkForwardRows = Array.isArray(breakdowns.walkForward) ? breakdowns.walkForward as Row[] : []; table(["Fold", "Status", "Training period", "Test period", "Candidates", "Eligible", "Selected", "OOS trades"], walkForwardRows.map((row) => [row.fold, row.status, row.trainingPeriod, row.testPeriod, row.totalCandidates ?? "NOT_APPLICABLE", row.eligibleCandidates ?? "NOT_APPLICABLE", row.selectedCandidate ?? "NOT_APPLICABLE", row.oosTrades ?? "NOT_APPLICABLE"]), [30, 75, 90, 90, 55, 55, 60, 60]); walkForwardRows.forEach((row) => fields([[`Fold ${row.fold} parameters`, row.selectedParameters == null ? "NOT_APPLICABLE" : JSON.stringify(row.selectedParameters)], [`Fold ${row.fold} training metrics`, row.trainingTrades == null ? "NOT_APPLICABLE" : `${row.trainingTrades} trades / ${number(row.trainingNetProfit)} P&L / PF ${number(row.trainingProfitFactor, 3)} / DD ${number(row.trainingDrawdown)}%`], [`Fold ${row.fold} OOS metrics`, row.oosTrades == null ? "NOT_APPLICABLE - no out-of-sample test executed" : `${row.oosTrades} trades / ${number(row.oosNetProfit)} P&L / PF ${number(row.oosProfitFactor, 3)}`], [`Fold ${row.fold} rejection reason`, row.rejectionReason ?? "None"]])); if (breakdowns.walkForwardSummary) fields(Object.entries(breakdowns.walkForwardSummary as Row).map(([key, value]) => [key, value]));
    title("Warnings and execution log"); table(["Warning"], Array.isArray(result.warnings) && result.warnings.length ? (result.warnings as unknown[]).map((warning) => [warning]) : [["No warnings reported"]], [515]); table(["Timestamp", "Level", "Stage", "Event", "Message"], input.logs.map((log) => [date(log.timestamp), log.level, log.stage, log.event_type, log.message]), [112, 48, 85, 95, 175]);
    title("Trade appendix"); table(["#", "Side", "Entry", "Exit", "Qty", "Net P&L", "Fees", "Reason"], input.trades.map((trade) => [trade.sequence, trade.side, `${date(trade.entry_time)} @ ${number(trade.entry_price, 4)}`, `${date(trade.exit_time)} @ ${number(trade.exit_price, 4)}`, number(trade.quantity, 5), number(trade.net_pnl), number(trade.fees), trade.exit_reason]), [25, 40, 112, 112, 53, 57, 48, 68]);
    footer(); document.end();
  });
}
