import PDFDocument from "pdfkit";

type Row = Record<string, unknown>;
const clean = (value: unknown) => String(value ?? "-").replace(/[^\x20-\x7E]/g, "?");
const number = (value: unknown, digits = 2) => Number(value ?? 0).toLocaleString("en-US", { maximumFractionDigits: digits });
const date = (value: unknown) => {
  if (!value) return "-";
  const numeric = Number(value);
  const parsed = new Date(Number.isFinite(numeric) && numeric > 1_000_000_000 ? numeric : String(value));
  return Number.isNaN(parsed.getTime()) ? clean(value) : parsed.toISOString().replace("T", " ").replace(/\.\d{3}Z$/, " UTC");
};

export async function verificationReportPdf(input: { run: Row; version: Row | null; result: Row; trades: Row[]; logs: Row[] }) {
  return await new Promise<Buffer>((resolve, reject) => {
    const document = new PDFDocument({ size: "A4", margin: 40, info: { Title: `Treidin verification ${clean(input.run.name)}`, Author: "Treidin" } });
    const chunks: Buffer[] = []; document.on("data", (chunk: Buffer) => chunks.push(chunk)); document.on("end", () => resolve(Buffer.concat(chunks))); document.on("error", reject);
    let page = 1;
    const header = () => { document.rect(0, 0, 595, 54).fill("#07111e"); document.fillColor("#2dd4bf").font("Helvetica-Bold").fontSize(13).text("TREIDIN - STRATEGY VERIFICATION REPORT", 40, 20); document.fillColor("#9fb0c2").font("Helvetica").fontSize(8).text(`Generated ${new Date().toISOString().replace("T", " ").slice(0, 19)} UTC`, 390, 23, { width: 165, align: "right" }); document.x = 40; document.y = 72; };
    const footer = () => { document.fillColor("#718096").font("Helvetica").fontSize(8).text(`Treidin local verification - page ${page}`, 40, 790, { width: 515, align: "center" }); };
    const nextPage = () => { footer(); document.addPage(); page++; header(); };
    const requireSpace = (height: number) => { if (document.y + height > 780) nextPage(); };
    const title = (text: string) => { requireSpace(28); document.moveTo(40, document.y).lineTo(555, document.y).strokeColor("#cbd5e1").lineWidth(.5).stroke(); document.moveDown(.55).fillColor("#0f5f9e").font("Helvetica-Bold").fontSize(12).text(clean(text)); document.moveDown(.35); };
    const fields = (items: Array<[string, unknown]>) => { for (const [label, value] of items) { requireSpace(17); const y = document.y; document.fillColor("#64748b").font("Helvetica-Bold").fontSize(8).text(clean(label).toUpperCase(), 40, y, { width: 185 }); document.fillColor("#1f2937").rect(225, y - 3, 330, 14).fill(); document.fillColor("#e2e8f0").font("Helvetica").fontSize(8).text(clean(value), 231, y, { width: 318 }); document.y = y + 17; } document.moveDown(.45); };
    const table = (headers: string[], rows: unknown[][], widths: number[]) => { const drawHeader = () => { requireSpace(24); const y = document.y; document.rect(40, y - 3, 515, 17).fill("#0f2742"); let x = 44; headers.forEach((item, index) => { document.fillColor("#cbd5e1").font("Helvetica-Bold").fontSize(7).text(clean(item), x, y + 2, { width: widths[index] - 5, ellipsis: true }); x += widths[index]; }); document.y = y + 19; };
      drawHeader(); rows.forEach((row) => { requireSpace(15); if (document.y + 15 > 780) { nextPage(); drawHeader(); } const y = document.y; let x = 44; row.forEach((item, index) => { document.fillColor("#28394c").font("Helvetica").fontSize(7).text(clean(item), x, y, { width: widths[index] - 5, ellipsis: true }); x += widths[index]; }); document.strokeColor("#d9e2ec").opacity(.2).moveTo(40, y + 12).lineTo(555, y + 12).stroke().opacity(1); document.y = y + 14; }); document.moveDown(.5); };
    header();
    const result = input.result, metrics = (result.metrics ?? {}) as Row, breakdowns = (result.breakdowns ?? {}) as Row, scorecard = (result.scorecard ?? {}) as Row;
    document.fillColor("#0f172a").font("Helvetica-Bold").fontSize(20).text(clean(input.run.name)); document.fillColor("#64748b").font("Helvetica").fontSize(9).text("Complete, reproducible historical strategy test", { continued: false }); document.moveDown(.8);
    title("Run identity"); fields([["Run ID", input.run.id], ["Strategy version", input.run.strategyVersionId], ["Symbol / profile", `${input.run.symbol} / ${input.run.profile}`], ["Requested range", `${date(input.run.requestedStart)} to ${date(input.run.requestedEnd)}`], ["Configuration hash", input.run.configurationHash], ["Random seed", input.run.randomSeed]]);
    title("Core performance"); fields([["Net profit", `${number(metrics.netProfit)} (${number(metrics.netProfitPct)}%)`], ["Final equity", number(metrics.equityFinal)], ["Trade count", metrics.tradeCount], ["Profit factor", number(metrics.profitFactor, 3)], ["Win rate", `${number(metrics.winRate, 1)}%`], ["Maximum drawdown", `${number(metrics.maxDrawdown)} (${number(metrics.maxDrawdownPct)}%)`], ["Sharpe / Sortino", `${number(metrics.sharpe, 3)} / ${number(metrics.sortino, 3)}`], ["Scorecard", `${scorecard.status ?? "-"} (${scorecard.score ?? "-"})`]]);
    title("Strategy configuration"); fields([["Trigger / execution timeframe", `${(input.version?.configuration as Row | undefined)?.triggerTimeframe ?? "-"} / ${(input.version?.configuration as Row | undefined)?.executionTimeframe ?? "-"}`], ["Directions", (input.version?.configuration as Row | undefined)?.directions], ["Stop / target", `${((input.version?.configuration as Row | undefined)?.stop as Row | undefined)?.type ?? "-"} / ${((input.version?.configuration as Row | undefined)?.takeProfit as Row | undefined)?.type ?? "-"}`], ["Registry version", input.version?.indicatorRegistryVersion]]);
    title("Risk, execution and exposure"); table(["Metric", "Value", "Metric", "Value"], [["Gross profit", number(metrics.grossProfit), "Gross loss", number(metrics.grossLoss)], ["Total fees", number(metrics.totalFees), "Slippage impact", number(metrics.totalSlippageImpact)], ["Funding", number(metrics.totalFunding), "Time in market", `${number(metrics.timeInMarketPct)}%`], ["Risk of ruin", `${number(metrics.riskOfRuinPct)}%`, "Annualized return", `${number(metrics.annualizedReturnPct)}%`], ["Average MAE", `${number(metrics.averageMaePct)}%`, "Average MFE", `${number(metrics.averageMfePct)}%`]], [130, 128, 130, 127]);
    const mc = breakdowns.monteCarlo as Row | null, oos = (breakdowns.outOfSample ?? {}) as Row, dataAudit = (breakdowns.dataAudit ?? {}) as Row;
    title("Out-of-sample and Monte Carlo"); fields([["OOS period", `${date(oos.start)} to ${date(oos.end)}`], ["OOS net profit / PF", `${number(oos.netProfit)} / ${number(oos.profitFactor, 3)}`], ["Monte Carlo simulations", mc?.count ?? "Not run"], ["Monte Carlo final equity P5 / median / P95", mc ? `${number(mc.p05FinalEquity)} / ${number(mc.medianFinalEquity)} / ${number(mc.p95FinalEquity)}` : "-"], ["Monte Carlo probability of profit", mc ? `${number(mc.probabilityOfProfit, 1)}%` : "-"]]);
    title("Scorecard and robustness"); table(["Check", "Status"], Array.isArray(scorecard.checks) ? (scorecard.checks as Row[]).map((check) => [check.name, check.passed ? "PASS" : "FAIL"]) : [], [350, 165]); table(["Scenario", "Trades", "Net profit", "Profit factor", "Max drawdown %"], Array.isArray(breakdowns.costStress) ? (breakdowns.costStress as Row[]).map((row) => [row.name, row.trades, number(row.netProfit), number(row.profitFactor, 3), number(row.maxDrawdownPct)]) : [], [145, 70, 105, 100, 95]);
    title("Data quality and bias audit"); fields([["Closed / complete candles only", dataAudit.usesClosedCompleteCandlesOnly ? "PASS" : "FAIL"], ["Point-in-time feature access", dataAudit.pointInTimeFeatureAccess ? "PASS" : "FAIL"], ["Exchange rules applied", dataAudit.exchangeRulesApplied ? "YES" : "NO"], ["Required timeframes", Array.isArray(dataAudit.requiredTimeframes) ? dataAudit.requiredTimeframes.join(", ") : "-"], ["Data fingerprint", (dataAudit.fingerprint as Row | undefined)?.checksum ?? "-"], ["Known limitations", Array.isArray(dataAudit.knownLimitations) && dataAudit.knownLimitations.length ? dataAudit.knownLimitations.join("; ") : "None reported"]]);
    title("Market regimes and walk-forward"); table(["Regime", "Trades", "Net profit", "Win rate %"], Array.isArray(breakdowns.marketRegimes) ? (breakdowns.marketRegimes as Row[]).map((row) => [row.regime, row.trades, number(row.netProfit), number(row.winRate, 1)]) : [], [170, 95, 130, 120]); table(["Fold", "Period multiplier", "Trades", "Net profit", "Profit factor"], Array.isArray(breakdowns.walkForward) ? (breakdowns.walkForward as Row[]).map((row) => [row.fold, number(row.selectedPeriodMultiplier, 2), row.trades, number(row.netProfit), number(row.profitFactor, 3)]) : [], [80, 130, 80, 120, 105]);
    title("Warnings and execution log"); table(["Warning"], Array.isArray(result.warnings) && result.warnings.length ? (result.warnings as unknown[]).map((warning) => [warning]) : [["No warnings reported"]], [515]); table(["Timestamp", "Level", "Stage", "Event", "Message"], input.logs.map((log) => [date(log.timestamp), log.level, log.stage, log.event_type, log.message]), [112, 48, 85, 95, 175]);
    title("Trade appendix"); table(["#", "Side", "Entry", "Exit", "Qty", "Net P&L", "Fees", "Reason"], input.trades.map((trade) => [trade.sequence, trade.side, `${date(trade.entry_time)} @ ${number(trade.entry_price, 4)}`, `${date(trade.exit_time)} @ ${number(trade.exit_price, 4)}`, number(trade.quantity, 5), number(trade.net_pnl), number(trade.fees), trade.exit_reason]), [25, 40, 112, 112, 53, 57, 48, 68]);
    footer(); document.end();
  });
}
