import { randomUUID } from "node:crypto";
import { sqlite } from "../db/database.js";
import type { StrategyConfig, StrategyLifecycle, StrategyOrigin, StrategyStatus } from "./model.js";

type Row = Record<string, unknown>; const asDate = (x: unknown) => x == null ? null : new Date(Number(x)); const json = <T>(x: unknown): T => JSON.parse(String(x));
const mapStrategy = (r: Row) => ({ id: String(r.id), name: String(r.name), description: String(r.description), tags: json<string[]>(r.tags_json), status: String(r.status), origin: String(r.origin ?? "MANUAL") as StrategyOrigin, lifecycle: String(r.lifecycle ?? (r.status === "ARCHIVED" ? "RETIRED" : "DRAFT")) as StrategyLifecycle, clonedFromStrategyId: r.cloned_from_strategy_id ? String(r.cloned_from_strategy_id) : null, sourceResearchRunId: r.source_research_run_id ? String(r.source_research_run_id) : null, sourceCandidateId: r.source_candidate_id ? String(r.source_candidate_id) : null, sourceNormalizedHash: r.source_normalized_hash ? String(r.source_normalized_hash) : null, createdAt: asDate(r.created_at)!, updatedAt: asDate(r.updated_at)! });
const mapVersion = (r: Row) => ({ id: String(r.id), strategyId: String(r.strategy_id), versionNumber: Number(r.version_number), parentVersionId: r.parent_version_id ? String(r.parent_version_id) : null, changeNotes: String(r.change_notes), configuration: json<StrategyConfig>(r.configuration_json), configurationHash: String(r.configuration_hash), indicatorRegistryVersion: String(r.indicator_registry_version), verificationStatus: String(r.verification_status) as StrategyStatus, createdAt: asDate(r.created_at)! });
const mapRun = (r: Row) => ({ id: String(r.id), strategyVersionId: String(r.strategy_version_id), name: String(r.name), symbol: String(r.symbol), market: String(r.market), requestedStart: asDate(r.requested_start)!, requestedEnd: asDate(r.requested_end)!, actualStart: asDate(r.actual_start), actualEnd: asDate(r.actual_end), status: String(r.status), stage: String(r.stage), progress: Number(r.progress), stageProgress: Number(r.stage_progress), candlesProcessed: Number(r.candles_processed), eventsProcessed: Number(r.events_processed), tradesSimulated: Number(r.trades_simulated), estimatedWork: Number(r.estimated_work), completedWork: Number(r.completed_work), profile: String(r.profile), options: json<Record<string, unknown>>(r.options_json), dataFingerprint: json<Record<string, unknown>>(r.data_fingerprint_json), configurationHash: String(r.configuration_hash), engineVersion: String(r.engine_version), metricsVersion: String(r.metrics_version), monteCarloEngineVersion: r.monte_carlo_engine_version ? String(r.monte_carlo_engine_version) : null, walkForwardEngineVersion: r.walk_forward_engine_version ? String(r.walk_forward_engine_version) : null, robustnessEngineVersion: r.robustness_engine_version ? String(r.robustness_engine_version) : null, stressEngineVersion: r.stress_engine_version ? String(r.stress_engine_version) : null, exportVersion: r.export_version ? String(r.export_version) : null, reportEngineVersion: r.report_engine_version ? String(r.report_engine_version) : null, auditStatus: r.audit_status ? String(r.audit_status) : null, auditUpdatedAt: asDate(r.audit_updated_at), randomSeed: Number(r.random_seed), cancelRequested: Boolean(r.cancel_requested), errorCode: r.error_code ? String(r.error_code) : null, errorMessage: r.error_message ? String(r.error_message) : null, createdAt: asDate(r.created_at)!, startedAt: asDate(r.started_at), completedAt: asDate(r.completed_at), updatedAt: asDate(r.updated_at)! });

export const strategyRepository = {
  async create(input: { name: string; description: string; tags: string[]; origin?: StrategyOrigin; lifecycle?: StrategyLifecycle; clonedFromStrategyId?: string | null; sourceResearchRunId?: string | null; sourceCandidateId?: string | null; sourceNormalizedHash?: string | null }) { const id = randomUUID(), now = Date.now(); await sqlite.writer.enqueue(4, "strategy-create", (db) => db.transaction(() => { db.prepare("INSERT INTO strategies(id,name,description,tags_json,origin,lifecycle,cloned_from_strategy_id,source_research_run_id,source_candidate_id,source_normalized_hash,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?)").run(id, input.name, input.description, JSON.stringify(input.tags), input.origin ?? "MANUAL", input.lifecycle ?? "DRAFT", input.clonedFromStrategyId ?? null, input.sourceResearchRunId ?? null, input.sourceCandidateId ?? null, input.sourceNormalizedHash ?? null, now, now); db.prepare("INSERT INTO strategy_events(id,strategy_id,event_type,created_at,details_json) VALUES(?,?,?,?,?)").run(randomUUID(), id, "STRATEGY_CREATED", now, JSON.stringify({ origin: input.origin ?? "MANUAL" })); })()); return this.get(id)!; },
  get(id: string) { const row = sqlite.reader.prepare("SELECT * FROM strategies WHERE id=?").get(id) as Row | undefined; return row ? mapStrategy(row) : null; },
  list() { return (sqlite.reader.prepare("SELECT * FROM strategies ORDER BY updated_at DESC").all() as Row[]).map(mapStrategy); },
  async archive(id: string) { const now = Date.now(); await sqlite.writer.enqueue(4, "strategy-archive", (db) => db.transaction(() => { db.prepare("UPDATE strategies SET status='ARCHIVED',lifecycle='RETIRED',updated_at=? WHERE id=?").run(now, id); db.prepare("INSERT INTO strategy_events(id,strategy_id,event_type,created_at,details_json) VALUES(?,?,?,?,?)").run(randomUUID(), id, "LIFECYCLE_CHANGED", now, JSON.stringify({ lifecycle: "RETIRED" })); })()); return this.get(id); },
  async setLifecycle(id: string, lifecycle: StrategyLifecycle) { const now = Date.now(); await sqlite.writer.enqueue(4, "strategy-lifecycle", (db) => db.transaction(() => { db.prepare("UPDATE strategies SET lifecycle=?,status=CASE WHEN ?='RETIRED' THEN 'ARCHIVED' ELSE 'DRAFT' END,updated_at=? WHERE id=?").run(lifecycle, lifecycle, now, id); db.prepare("INSERT INTO strategy_events(id,strategy_id,event_type,created_at,details_json) VALUES(?,?,?,?,?)").run(randomUUID(), id, "LIFECYCLE_CHANGED", now, JSON.stringify({ lifecycle })); })()); return this.get(id); },
  events(strategyId: string) { return (sqlite.reader.prepare("SELECT * FROM strategy_events WHERE strategy_id=? ORDER BY created_at DESC LIMIT 500").all(strategyId) as Row[]).map((row) => ({ ...row, details: json(row.details_json), createdAt: asDate(row.created_at) })); },
  versions(strategyId: string) { return (sqlite.reader.prepare("SELECT * FROM strategy_versions WHERE strategy_id=? ORDER BY version_number DESC").all(strategyId) as Row[]).map(mapVersion); },
  version(id: string) { const row = sqlite.reader.prepare("SELECT * FROM strategy_versions WHERE id=?").get(id) as Row | undefined; return row ? mapVersion(row) : null; },
  async archiveVersion(id: string) { await sqlite.writer.enqueue(4, "strategy-version-archive", (db) => db.prepare("UPDATE strategy_versions SET verification_status='ARCHIVED' WHERE id=?").run(id)); return this.version(id); },
  async applyVerificationOutcome(versionId: string, outcome: "VERIFIED" | "VERIFICATION_WARNING" | "VERIFICATION_FAILED", profile: string) { const now = Date.now(); await sqlite.writer.enqueue(4, "strategy-verification-outcome", (db) => db.transaction(() => { const version = db.prepare("SELECT strategy_id FROM strategy_versions WHERE id=?").get(versionId) as { strategy_id: string } | undefined; if (!version) return; db.prepare("UPDATE strategy_versions SET verification_status=? WHERE id=?").run(outcome, versionId); if (profile === "FULL" && outcome === "VERIFIED") { db.prepare("UPDATE strategies SET lifecycle='VERIFIED',updated_at=? WHERE id=? AND lifecycle <> 'RETIRED'").run(now, version.strategy_id); db.prepare("INSERT INTO strategy_events(id,strategy_id,event_type,created_at,details_json) VALUES(?,?,?,?,?)").run(randomUUID(), version.strategy_id, "FULL_VERIFICATION_PASSED", now, JSON.stringify({ strategyVersionId: versionId })); } else if (profile === "FULL") db.prepare("INSERT INTO strategy_events(id,strategy_id,event_type,created_at,details_json) VALUES(?,?,?,?,?)").run(randomUUID(), version.strategy_id, "FULL_VERIFICATION_COMPLETED", now, JSON.stringify({ strategyVersionId: versionId, outcome })); })()); return this.version(versionId); },
  async publish(strategyId: string, config: StrategyConfig, hash: string, registryVersion: string, changeNotes: string, parentVersionId?: string) { const id = randomUUID(), now = Date.now(); await sqlite.writer.enqueue(4, "strategy-version-publish", (db) => db.transaction(() => { const count = db.prepare("SELECT count(*) count FROM strategy_versions WHERE strategy_id=?").get(strategyId) as { count: number }; db.prepare("INSERT INTO strategy_versions(id,strategy_id,version_number,parent_version_id,change_notes,configuration_json,configuration_hash,indicator_registry_version,verification_status,created_at) VALUES(?,?,?,?,?,?,?,?,?,?)").run(id, strategyId, count.count + 1, parentVersionId ?? null, changeNotes, JSON.stringify(config), hash, registryVersion, "READY_FOR_VERIFICATION", now); db.prepare("UPDATE strategies SET lifecycle=CASE WHEN lifecycle='DRAFT' THEN 'READY_FOR_DEEP_VERIFICATION' ELSE lifecycle END,updated_at=? WHERE id=?").run(now, strategyId); db.prepare("INSERT INTO strategy_events(id,strategy_id,event_type,created_at,details_json) VALUES(?,?,?,?,?)").run(randomUUID(), strategyId, "VERSION_CREATED", now, JSON.stringify({ strategyVersionId: id, versionNumber: count.count + 1, parentVersionId: parentVersionId ?? null })); })()); return this.version(id)!; },
};

export const verificationRepository = {
  async create(input: Omit<ReturnType<typeof mapRun>, "id" | "status" | "stage" | "progress" | "stageProgress" | "candlesProcessed" | "eventsProcessed" | "tradesSimulated" | "completedWork" | "cancelRequested" | "errorCode" | "errorMessage" | "createdAt" | "startedAt" | "completedAt" | "updatedAt" | "auditStatus" | "auditUpdatedAt" | "walkForwardEngineVersion" | "robustnessEngineVersion" | "stressEngineVersion" | "reportEngineVersion"> & Partial<Pick<ReturnType<typeof mapRun>, "walkForwardEngineVersion" | "robustnessEngineVersion" | "stressEngineVersion" | "reportEngineVersion">>) { const id = randomUUID(), now = Date.now(); await sqlite.writer.enqueue(5, "verification-create", (db) => db.prepare("INSERT INTO verification_runs(id,strategy_version_id,name,symbol,market,requested_start,requested_end,actual_start,actual_end,status,stage,estimated_work,profile,options_json,data_fingerprint_json,configuration_hash,engine_version,metrics_version,monte_carlo_engine_version,walk_forward_engine_version,robustness_engine_version,stress_engine_version,export_version,report_engine_version,random_seed,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)").run(id, input.strategyVersionId, input.name, input.symbol, input.market, input.requestedStart.getTime(), input.requestedEnd.getTime(), input.actualStart?.getTime() ?? null, input.actualEnd?.getTime() ?? null, "QUEUED", "QUEUED", input.estimatedWork, input.profile, JSON.stringify(input.options), JSON.stringify(input.dataFingerprint), input.configurationHash, input.engineVersion, input.metricsVersion, input.monteCarloEngineVersion, input.walkForwardEngineVersion ?? "2026.09.eligible-selection.1", input.robustnessEngineVersion ?? "2026.09.accounting.1", input.stressEngineVersion ?? "2026.09.accounting.1", input.exportVersion, input.reportEngineVersion ?? "2026.09.accounting.1", input.randomSeed, now, now)); return this.get(id)!; },
  get(id: string) { const r = sqlite.reader.prepare("SELECT * FROM verification_runs WHERE id=?").get(id) as Row | undefined; return r ? mapRun(r) : null; },
  list() { let queuePosition = 0; return (sqlite.reader.prepare("SELECT * FROM verification_runs ORDER BY created_at DESC LIMIT 200").all() as Row[]).map(mapRun).map((run) => ({ ...run, queuePosition: run.status === "QUEUED" ? ++queuePosition : null })); },
  async update(id: string, fields: Record<string, unknown>) { const columns: Record<string, string> = { status: "status", stage: "stage", progress: "progress", stageProgress: "stage_progress", candlesProcessed: "candles_processed", eventsProcessed: "events_processed", tradesSimulated: "trades_simulated", completedWork: "completed_work", cancelRequested: "cancel_requested", errorCode: "error_code", errorMessage: "error_message", actualStart: "actual_start", actualEnd: "actual_end", startedAt: "started_at", completedAt: "completed_at", metricsVersion: "metrics_version", exportVersion: "export_version", reportEngineVersion: "report_engine_version" }; const items = Object.entries(fields).filter(([k]) => columns[k]); if (!items.length) return this.get(id); await sqlite.writer.enqueue(5, "verification-update", (db) => db.prepare(`UPDATE verification_runs SET ${items.map(([k]) => `${columns[k]}=?`).join(",")},updated_at=? WHERE id=?`).run(...items.map(([, v]) => v instanceof Date ? v.getTime() : typeof v === "boolean" ? Number(v) : v), Date.now(), id)); return this.get(id); },
  async updateAuditStatus(id: string, auditStatus: string) { const updatedAt = Date.now(); await sqlite.writer.enqueue(5, "verification-audit-status", (db) => db.prepare("UPDATE verification_runs SET audit_status=?,audit_updated_at=?,updated_at=? WHERE id=?").run(auditStatus, updatedAt, updatedAt, id)); return this.get(id); },
  async claimNext() { return sqlite.writer.enqueue(5, "verification-claim", (db) => db.transaction(() => { const r = db.prepare("SELECT * FROM verification_runs WHERE status='QUEUED' ORDER BY created_at LIMIT 1").get() as Row | undefined; if (!r) return null; const now = Date.now(); db.prepare("UPDATE verification_runs SET status='RUNNING',stage='LOADING_DATA',started_at=?,updated_at=? WHERE id=?").run(now, now, r.id); return mapRun({ ...r, status: "RUNNING", stage: "LOADING_DATA", started_at: now, updated_at: now }); })()); },
  async recoverInterrupted() { return sqlite.writer.enqueue(5, "verification-recover", (db) => db.prepare("UPDATE verification_runs SET status='QUEUED',stage='QUEUED',error_code='RESTART_RECOVERY',error_message='Recovered after process restart',updated_at=? WHERE status IN ('RUNNING','CANCELLING')").run(Date.now()).changes); },
  async cancel(id: string) { return this.update(id, { cancelRequested: true, status: "CANCELLING" }); },
  async log(id: string, level: string, stage: string, event: string, message: string, details?: unknown) { await sqlite.writer.enqueue(6, "verification-log", (db) => db.prepare("INSERT INTO verification_logs(id,verification_run_id,timestamp,level,component,stage,event_type,message,details_json) VALUES(?,?,?,?,?,?,?,?,?)").run(randomUUID(), id, Date.now(), level, "verification", stage, event, message, details === undefined ? null : JSON.stringify(details))); },
  logs(id: string) { return sqlite.reader.prepare("SELECT * FROM verification_logs WHERE verification_run_id=? ORDER BY timestamp LIMIT 2000").all(id); },
  async storeResult(id: string, result: { metrics: unknown; equityCurve: unknown; breakdowns: unknown; scorecard: unknown; funnel: unknown; warnings: unknown }) { await sqlite.writer.enqueue(6, "verification-result", (db) => db.prepare("INSERT OR REPLACE INTO verification_results(verification_run_id,metrics_json,equity_curve_json,breakdowns_json,scorecard_json,funnel_json,warnings_json,created_at) VALUES(?,?,?,?,?,?,?,?)").run(id, JSON.stringify(result.metrics), JSON.stringify(result.equityCurve), JSON.stringify(result.breakdowns), JSON.stringify(result.scorecard), JSON.stringify(result.funnel), JSON.stringify(result.warnings), Date.now())); },
  result(id: string) { const r = sqlite.reader.prepare("SELECT * FROM verification_results WHERE verification_run_id=?").get(id) as Row | undefined; return r ? { metrics: json(r.metrics_json), equityCurve: json(r.equity_curve_json), breakdowns: json(r.breakdowns_json), scorecard: json(r.scorecard_json), funnel: json(r.funnel_json), warnings: json(r.warnings_json) } : null; },
  async storeTrades(id: string, trades: Array<Record<string, unknown>>) { await sqlite.writer.enqueue(6, "verification-trades", (db) => { const q = db.prepare("INSERT INTO verification_trades(id,verification_run_id,sequence,side,entry_time,exit_time,entry_price,exit_price,quantity,gross_pnl,net_pnl,fees,return_pct,r_multiple,mae_pct,mfe_pct,holding_ms,entry_reason,exit_reason,details_json) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)"); return db.transaction(() => trades.forEach((t, sequence) => q.run(randomUUID(), id, sequence + 1, t.side, t.entryTime, t.exitTime, t.entryPrice, t.exitPrice, t.quantity, t.grossPnl, t.netPnl, t.fees, t.returnPct, t.rMultiple ?? null, t.maePct ?? null, t.mfePct ?? null, t.holdingMs, t.entryReason, t.exitReason, JSON.stringify(t.details ?? {}))))(); }); },
  trades(id: string, limit = 1000, offset = 0) { return sqlite.reader.prepare("SELECT * FROM verification_trades WHERE verification_run_id=? ORDER BY sequence LIMIT ? OFFSET ?").all(id, limit, offset); },
  iterateTrades(id: string) { return sqlite.reader.prepare("SELECT * FROM verification_trades WHERE verification_run_id=? ORDER BY sequence").iterate(id) as IterableIterator<Row>; },
  trade(id: string, sequence: number) { return sqlite.reader.prepare("SELECT * FROM verification_trades WHERE verification_run_id=? AND sequence=?").get(id, sequence) as Row | undefined; },
};
