import { randomUUID } from "node:crypto";
import { sqlite } from "../db/database.js";

type Row = Record<string, unknown>;
const date = (value: unknown) => value == null ? null : new Date(Number(value));
const json = <T>(value: unknown): T => JSON.parse(String(value));
const mapRun = (row: Row) => ({ id: String(row.id), name: String(row.name), description: String(row.description), symbol: String(row.symbol), directions: String(row.directions), triggerTimeframe: String(row.trigger_timeframe), executionTimeframe: String(row.execution_timeframe), status: String(row.status), health: String(row.health), stage: String(row.stage), progress: Number(row.progress), candidateBudget: Number(row.candidate_budget), generatedCount: Number(row.generated_count), duplicateCount: Number(row.duplicate_count), structurallyRejectedCount: Number(row.structurally_rejected_count), isTestedCount: Number(row.is_tested_count), isSurvivorCount: Number(row.is_survivor_count), oosTestedCount: Number(row.oos_tested_count), oosSurvivorCount: Number(row.oos_survivor_count), finalistCount: Number(row.finalist_count), holdoutTestedCount: Number(row.holdout_tested_count), promotedCount: Number(row.promoted_count), config: json<Record<string, unknown>>(row.config_json), periods: json<Record<string, unknown>>(row.periods_json), configHash: String(row.config_hash), datasetFingerprint: json<Record<string, unknown>>(row.dataset_fingerprint_json), engineVersion: String(row.engine_version), indicatorRegistryVersion: String(row.indicator_registry_version), searchAlgorithmVersion: String(row.search_algorithm_version), splitterVersion: String(row.splitter_version), randomSeed: Number(row.random_seed), holdoutEvaluated: Boolean(row.holdout_evaluated), holdoutExposed: Boolean(row.holdout_exposed), holdoutExposedAt: date(row.holdout_exposed_at), errorCode: row.error_code ? String(row.error_code) : null, errorMessage: row.error_message ? String(row.error_message) : null, createdAt: date(row.created_at)!, startedAt: date(row.started_at), completedAt: date(row.completed_at), updatedAt: date(row.updated_at)! });
const mapCandidate = (row: Row) => ({ id: String(row.id), researchRunId: String(row.research_run_id), generationIndex: Number(row.generation_index), status: String(row.status), family: String(row.family), direction: String(row.direction), rawAst: json<Record<string, unknown>>(row.raw_ast_json), normalizedAst: json<Record<string, unknown>>(row.normalized_ast_json), normalizedHash: String(row.normalized_hash), configuration: json<Record<string, unknown>>(row.configuration_json), complexityScore: Number(row.complexity_score), metrics: json<Record<string, unknown>>(row.metrics_json), score: row.score == null ? null : Number(row.score), paretoRank: row.pareto_rank == null ? null : Number(row.pareto_rank), rejectionStage: row.rejection_stage ? String(row.rejection_stage) : null, rejectionReason: row.rejection_reason ? String(row.rejection_reason) : null, promotedStrategyId: row.promoted_strategy_id ? String(row.promoted_strategy_id) : null, createdAt: date(row.created_at)!, updatedAt: date(row.updated_at)! });

export const researchRepository = {
  async create(input: { name: string; description: string; symbol: string; directions: string; triggerTimeframe: string; executionTimeframe: string; candidateBudget: number; config: unknown; periods: unknown; configHash: string; datasetFingerprint: unknown; engineVersion: string; indicatorRegistryVersion: string; searchAlgorithmVersion: string; splitterVersion: string; randomSeed: number }) { const id = randomUUID(), now = Date.now(); await sqlite.writer.enqueue(6, "research-run-create", (db) => db.prepare("INSERT INTO research_runs(id,name,description,symbol,directions,trigger_timeframe,execution_timeframe,status,health,stage,candidate_budget,config_json,periods_json,config_hash,dataset_fingerprint_json,engine_version,indicator_registry_version,search_algorithm_version,splitter_version,random_seed,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)").run(id, input.name, input.description, input.symbol, input.directions, input.triggerTimeframe, input.executionTimeframe, "DRAFT", "UNKNOWN", "DRAFT", input.candidateBudget, JSON.stringify(input.config), JSON.stringify(input.periods), input.configHash, JSON.stringify(input.datasetFingerprint), input.engineVersion, input.indicatorRegistryVersion, input.searchAlgorithmVersion, input.splitterVersion, input.randomSeed, now, now)); return this.get(id)!; },
  get(id: string) { const row = sqlite.reader.prepare("SELECT * FROM research_runs WHERE id=?").get(id) as Row | undefined; return row ? mapRun(row) : null; },
  list() { return (sqlite.reader.prepare("SELECT * FROM research_runs ORDER BY created_at DESC LIMIT 200").all() as Row[]).map(mapRun); },
  async update(id: string, fields: Record<string, unknown>) { const columns: Record<string, string> = { status: "status", health: "health", stage: "stage", progress: "progress", generatedCount: "generated_count", duplicateCount: "duplicate_count", structurallyRejectedCount: "structurally_rejected_count", isTestedCount: "is_tested_count", isSurvivorCount: "is_survivor_count", oosTestedCount: "oos_tested_count", oosSurvivorCount: "oos_survivor_count", finalistCount: "finalist_count", holdoutTestedCount: "holdout_tested_count", promotedCount: "promoted_count", holdoutEvaluated: "holdout_evaluated", holdoutExposed: "holdout_exposed", holdoutExposedAt: "holdout_exposed_at", errorCode: "error_code", errorMessage: "error_message", startedAt: "started_at", completedAt: "completed_at" }; const values = Object.entries(fields).filter(([key]) => columns[key]); if (!values.length) return this.get(id); await sqlite.writer.enqueue(6, "research-run-update", (db) => db.prepare(`UPDATE research_runs SET ${values.map(([key]) => `${columns[key]}=?`).join(",")},updated_at=? WHERE id=?`).run(...values.map(([, value]) => value instanceof Date ? value.getTime() : typeof value === "boolean" ? Number(value) : value), Date.now(), id)); return this.get(id); },
  async launch(id: string) { return this.update(id, { status: "QUEUED", health: "HEALTHY", stage: "QUEUED", progress: 0, errorCode: null, errorMessage: null }); },
  async claimNext() { return sqlite.writer.enqueue(6, "research-run-claim", (db) => db.transaction(() => { const row = db.prepare("SELECT * FROM research_runs WHERE status IN ('QUEUED','RESUMING') ORDER BY created_at LIMIT 1").get() as Row | undefined; if (!row) return null; const now = Date.now(); db.prepare("UPDATE research_runs SET status='RUNNING',health='HEALTHY',stage='INITIALIZING',started_at=COALESCE(started_at,?),updated_at=? WHERE id=?").run(now, now, row.id); return mapRun({ ...row, status: "RUNNING", health: "HEALTHY", stage: "INITIALIZING", started_at: row.started_at ?? now, updated_at: now }); })()); },
  async requestPause(id: string) { return this.update(id, { status: "PAUSING" }); },
  async requestCancel(id: string) { return this.update(id, { status: "CANCELLING" }); },
  async exposeHoldout(id: string) { const run = this.get(id); if (!run || !run.holdoutEvaluated || run.holdoutExposed) return run; const exposedAt = new Date(); await this.update(id, { holdoutExposed: true, holdoutExposedAt: exposedAt }); await this.log(id, "INFO", "HOLDOUT", "HOLDOUT_EXPOSED", "Holdout results exposed to the user", { exposedAt: exposedAt.toISOString() }); return this.get(id); },
  async recoverInterrupted() { return sqlite.writer.enqueue(6, "research-run-recover", (db) => db.prepare("UPDATE research_runs SET status='QUEUED',stage='QUEUED',error_code='RESTART_RECOVERY',error_message='Recovered after process restart',updated_at=? WHERE status IN ('RUNNING','PAUSING','CANCELLING')").run(Date.now()).changes); },
  async log(id: string, level: string, stage: string, eventType: string, message: string, details?: unknown) { await sqlite.writer.enqueue(7, "research-event", (db) => db.prepare("INSERT INTO research_events(id,research_run_id,timestamp,level,stage,event_type,message,details_json) VALUES(?,?,?,?,?,?,?,?)").run(randomUUID(), id, Date.now(), level, stage, eventType, message, details === undefined ? null : JSON.stringify(details))); },
  events(id: string) { return (sqlite.reader.prepare("SELECT * FROM research_events WHERE research_run_id=? ORDER BY timestamp DESC LIMIT 2000").all(id) as Row[]).map((row) => ({ ...row, details: row.details_json ? json(row.details_json) : null, timestamp: date(row.timestamp) })); },
  async insertCandidate(input: { researchRunId: string; generationIndex: number; status: string; family: string; direction: string; rawAst: unknown; normalizedAst: unknown; normalizedHash: string; configuration: unknown; complexityScore: number; metrics?: unknown; score?: number | null; paretoRank?: number | null; rejectionStage?: string | null; rejectionReason?: string | null }) { const id = randomUUID(), now = Date.now(); try { await sqlite.writer.enqueue(7, "research-candidate-create", (db) => db.prepare("INSERT INTO research_candidates(id,research_run_id,generation_index,status,family,direction,raw_ast_json,normalized_ast_json,normalized_hash,configuration_json,complexity_score,metrics_json,score,pareto_rank,rejection_stage,rejection_reason,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)").run(id, input.researchRunId, input.generationIndex, input.status, input.family, input.direction, JSON.stringify(input.rawAst), JSON.stringify(input.normalizedAst), input.normalizedHash, JSON.stringify(input.configuration), input.complexityScore, JSON.stringify(input.metrics ?? {}), input.score ?? null, input.paretoRank ?? null, input.rejectionStage ?? null, input.rejectionReason ?? null, now, now)); return this.candidate(id)!; } catch (error) { if ((error as { code?: string }).code === "SQLITE_CONSTRAINT_UNIQUE") return null; throw error; } },
  candidate(id: string) { const row = sqlite.reader.prepare("SELECT * FROM research_candidates WHERE id=?").get(id) as Row | undefined; return row ? mapCandidate(row) : null; },
  async updateCandidate(id: string, fields: { status?: string; metrics?: unknown; score?: number | null; paretoRank?: number | null; rejectionStage?: string | null; rejectionReason?: string | null; promotedStrategyId?: string | null }) { const columns: Record<string, string> = { status: "status", metrics: "metrics_json", score: "score", paretoRank: "pareto_rank", rejectionStage: "rejection_stage", rejectionReason: "rejection_reason", promotedStrategyId: "promoted_strategy_id" }; const values = Object.entries(fields).filter(([key]) => columns[key]); if (!values.length) return this.candidate(id); await sqlite.writer.enqueue(7, "research-candidate-update", (db) => db.prepare(`UPDATE research_candidates SET ${values.map(([key]) => `${columns[key]}=?`).join(",")},updated_at=? WHERE id=?`).run(...values.map(([key, value]) => key === "metrics" ? JSON.stringify(value) : value), Date.now(), id)); return this.candidate(id); },
  candidates(runId: string, limit = 100, offset = 0) { return (sqlite.reader.prepare("SELECT * FROM research_candidates WHERE research_run_id=? ORDER BY score DESC NULLS LAST, generation_index LIMIT ? OFFSET ?").all(runId, limit, offset) as Row[]).map(mapCandidate); },
  candidateCount(runId: string) { return Number((sqlite.reader.prepare("SELECT count(*) count FROM research_candidates WHERE research_run_id=?").get(runId) as { count: number }).count); },
  async recordPromotion(input: { candidateId: string; runId: string; strategyId: string; strategyVersionId: string; verificationRunId?: string | null; actor?: string | null; note?: string | null }) { const id = randomUUID(), now = Date.now(); await sqlite.writer.enqueue(6, "research-candidate-promotion", (db) => db.transaction(() => { db.prepare("INSERT INTO research_candidate_promotions(id,research_candidate_id,research_run_id,strategy_id,strategy_version_id,verification_run_id,actor,note,created_at) VALUES(?,?,?,?,?,?,?,?,?)").run(id, input.candidateId, input.runId, input.strategyId, input.strategyVersionId, input.verificationRunId ?? null, input.actor ?? null, input.note ?? null, now); db.prepare("UPDATE research_candidates SET status='PROMOTED',promoted_strategy_id=?,updated_at=? WHERE id=?").run(input.strategyId, now, input.candidateId); db.prepare("UPDATE research_runs SET promoted_count=promoted_count+1,updated_at=? WHERE id=?").run(now, input.runId); })()); return { id, createdAt: new Date(now) }; },
};
