import { randomUUID } from "node:crypto";
import { sqlite } from "../db/database.js";

type Row = Record<string, unknown>;
const date = (value: unknown) => value == null ? null : new Date(Number(value));
const json = <T>(value: unknown, fallback: T): T => { if (value == null || value === "") return fallback; try { return JSON.parse(String(value)) as T; } catch { return fallback; } };
const bool = (value: unknown) => Number(value ?? 0) === 1;
const mapRun = (row: Row) => ({
  id: String(row.id), name: String(row.name), description: String(row.description), symbol: String(row.symbol), directions: String(row.directions), triggerTimeframe: String(row.trigger_timeframe), executionTimeframe: String(row.execution_timeframe), status: String(row.status), health: String(row.health), stage: String(row.stage), progress: Number(row.progress), candidateBudget: Number(row.candidate_budget), generatedCount: Number(row.generated_count), duplicateCount: Number(row.duplicate_count), structurallyRejectedCount: Number(row.structurally_rejected_count), isTestedCount: Number(row.is_tested_count), isSurvivorCount: Number(row.is_survivor_count), oosTestedCount: Number(row.oos_tested_count), oosSurvivorCount: Number(row.oos_survivor_count), finalistCount: Number(row.finalist_count), holdoutTestedCount: Number(row.holdout_tested_count), promotedCount: Number(row.promoted_count),
  generationAttemptCount: Number(row.generation_attempt_count ?? 0), generatedRawCount: Number(row.generated_raw_count ?? 0), staticRejectedCount: Number(row.static_rejected_count ?? row.structurally_rejected_count ?? 0), preflightRejectedCount: Number(row.preflight_rejected_count ?? 0), exactDuplicateCount: Number(row.exact_duplicate_count ?? row.duplicate_count ?? 0), semanticDuplicateCount: Number(row.semantic_duplicate_count ?? 0), acceptedCandidateCount: Number(row.accepted_candidate_count ?? 0), evaluatedCandidateCount: Number(row.evaluated_candidate_count ?? 0), unevaluatedCandidateCount: Number(row.unevaluated_candidate_count ?? 0), generationExhausted: bool(row.generation_exhausted), generationExhaustionReason: row.generation_exhaustion_reason ? String(row.generation_exhaustion_reason) : null, completionReason: row.completion_reason ? String(row.completion_reason) : null, grammarVersion: String(row.grammar_version ?? "legacy"), generationPolicy: json<Record<string, unknown>>(row.generation_policy_json, {}), validationPolicy: json<Record<string, unknown>>(row.validation_policy_json, {}), deduplicationPolicy: json<Record<string, unknown>>(row.deduplication_policy_json, {}), costModel: json<Record<string, unknown>>(row.cost_model_json, {}),
  config: json<Record<string, unknown>>(row.config_json, {}), periods: json<Record<string, unknown>>(row.periods_json, {}), configHash: String(row.config_hash), datasetFingerprint: json<Record<string, unknown>>(row.dataset_fingerprint_json, {}), engineVersion: String(row.engine_version), indicatorRegistryVersion: String(row.indicator_registry_version), searchAlgorithmVersion: String(row.search_algorithm_version), splitterVersion: String(row.splitter_version), randomSeed: Number(row.random_seed), holdoutEvaluated: bool(row.holdout_evaluated), holdoutExposed: bool(row.holdout_exposed), holdoutExposedAt: date(row.holdout_exposed_at), errorCode: row.error_code ? String(row.error_code) : null, errorMessage: row.error_message ? String(row.error_message) : null, createdAt: date(row.created_at)!, startedAt: date(row.started_at), completedAt: date(row.completed_at), updatedAt: date(row.updated_at)!,
});
const mapCandidate = (row: Row) => ({
  id: String(row.id), researchRunId: String(row.research_run_id), generationIndex: Number(row.generation_index), status: String(row.status), family: String(row.family), direction: String(row.direction), rawAst: json<Record<string, unknown>>(row.raw_ast_json, {}), normalizedAst: json<Record<string, unknown>>(row.normalized_ast_json, {}), normalizedHash: String(row.normalized_hash), semanticFingerprint: row.semantic_fingerprint ? String(row.semantic_fingerprint) : null, configuration: json<Record<string, unknown>>(row.configuration_json, {}), complexityScore: Number(row.complexity_score), complexityBreakdown: json<Record<string, unknown>>(row.complexity_breakdown_json, {}), metrics: json<Record<string, unknown>>(row.metrics_json, {}), preflightMetrics: json<Record<string, unknown>>(row.preflight_metrics_json, {}), score: row.score == null ? null : Number(row.score), paretoRank: row.pareto_rank == null ? null : Number(row.pareto_rank), rejectionStage: row.rejection_stage ? String(row.rejection_stage) : null, rejectionReason: row.rejection_reason ? String(row.rejection_reason) : null, stageRejectionReasons: json<Record<string, unknown>>(row.stage_rejection_reasons_json, {}), validationStatus: row.validation_status ? String(row.validation_status) : null, validationErrors: json<unknown[]>(row.validation_errors_json, []), generationAttemptIndex: row.generation_attempt_index == null ? null : Number(row.generation_attempt_index), duplicateOfCandidateId: row.duplicate_of_candidate_id ? String(row.duplicate_of_candidate_id) : null, terminalReason: row.terminal_reason ? String(row.terminal_reason) : null, humanDescription: row.human_description ? String(row.human_description) : null, generatorVersion: row.generator_version ? String(row.generator_version) : null, grammarVersion: row.grammar_version ? String(row.grammar_version) : null, registryVersion: row.registry_version ? String(row.registry_version) : null, promotedStrategyId: row.promoted_strategy_id ? String(row.promoted_strategy_id) : null, createdAt: date(row.created_at)!, updatedAt: date(row.updated_at)!,
});

const runTransitions: Record<string, string[]> = { DRAFT: ["QUEUED", "FAILED", "CANCELLED"], QUEUED: ["RUNNING", "CANCELLING", "CANCELLED", "FAILED"], INITIALIZING: ["RUNNING", "FAILED", "CANCELLING"], RUNNING: ["PAUSING", "CANCELLING", "COMPLETED", "FAILED"], PAUSING: ["PAUSED", "CANCELLING", "FAILED"], PAUSED: ["RESUMING", "QUEUED", "CANCELLING", "CANCELLED"], RESUMING: ["RUNNING", "FAILED", "CANCELLING"], COMPLETED: [], FAILED: ["QUEUED"], CANCELLING: ["CANCELLED", "FAILED"], CANCELLED: ["QUEUED"], };
const terminalCandidateStatuses = new Set(["STRUCTURAL_REJECTED", "IS_REJECTED", "OOS_REJECTED", "HOLDOUT_REJECTED", "COMPLETED", "PROMOTED", "PINNED", "REJECTED", "EVALUATION_FAILED"]);
const assertRunTransition = (from: string, to: string) => { if (from === to || runTransitions[from]?.includes(to)) return; throw new Error(`Invalid Research Run transition ${from} -> ${to}`); };

export const researchRepository = {
  async create(input: { name: string; description: string; symbol: string; directions: string; triggerTimeframe: string; executionTimeframe: string; candidateBudget: number; config: unknown; periods: unknown; configHash: string; datasetFingerprint: unknown; engineVersion: string; indicatorRegistryVersion: string; searchAlgorithmVersion: string; splitterVersion: string; randomSeed: number }) {
    const id = randomUUID(), now = Date.now();
    await sqlite.writer.enqueue(6, "research-run-create", (db) => db.prepare("INSERT INTO research_runs(id,name,description,symbol,directions,trigger_timeframe,execution_timeframe,status,health,stage,candidate_budget,config_json,periods_json,config_hash,dataset_fingerprint_json,engine_version,indicator_registry_version,search_algorithm_version,splitter_version,random_seed,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)").run(id, input.name, input.description, input.symbol, input.directions, input.triggerTimeframe, input.executionTimeframe, "DRAFT", "UNKNOWN", "DRAFT", input.candidateBudget, JSON.stringify(input.config), JSON.stringify(input.periods), input.configHash, JSON.stringify(input.datasetFingerprint), input.engineVersion, input.indicatorRegistryVersion, input.searchAlgorithmVersion, input.splitterVersion, input.randomSeed, now, now));
    return this.get(id)!;
  },
  get(id: string) { const row = sqlite.reader.prepare("SELECT * FROM research_runs WHERE id=?").get(id) as Row | undefined; return row ? mapRun(row) : null; },
  list() { return (sqlite.reader.prepare("SELECT * FROM research_runs ORDER BY created_at DESC LIMIT 200").all() as Row[]).map(mapRun); },
  async delete(id: string) { return sqlite.writer.enqueue(6, "research-run-delete", (db) => db.transaction(() => { const promotions = db.prepare("SELECT count(*) count FROM research_candidate_promotions WHERE research_run_id=?").get(id) as { count: number }; if (Number(promotions.count) > 0) return false; return db.prepare("DELETE FROM research_runs WHERE id=?").run(id).changes > 0; })()); },
  async update(id: string, fields: Record<string, unknown>) {
    const current = this.get(id); if (!current) return null;
    const columns: Record<string, string> = { status: "status", health: "health", stage: "stage", progress: "progress", generatedCount: "generated_count", duplicateCount: "duplicate_count", structurallyRejectedCount: "structurally_rejected_count", isTestedCount: "is_tested_count", isSurvivorCount: "is_survivor_count", oosTestedCount: "oos_tested_count", oosSurvivorCount: "oos_survivor_count", finalistCount: "finalist_count", holdoutTestedCount: "holdout_tested_count", promotedCount: "promoted_count", generationAttemptCount: "generation_attempt_count", generatedRawCount: "generated_raw_count", staticRejectedCount: "static_rejected_count", preflightRejectedCount: "preflight_rejected_count", exactDuplicateCount: "exact_duplicate_count", semanticDuplicateCount: "semantic_duplicate_count", acceptedCandidateCount: "accepted_candidate_count", evaluatedCandidateCount: "evaluated_candidate_count", unevaluatedCandidateCount: "unevaluated_candidate_count", generationExhausted: "generation_exhausted", generationExhaustionReason: "generation_exhaustion_reason", completionReason: "completion_reason", grammarVersion: "grammar_version", generationPolicy: "generation_policy_json", validationPolicy: "validation_policy_json", deduplicationPolicy: "deduplication_policy_json", costModel: "cost_model_json", holdoutEvaluated: "holdout_evaluated", holdoutExposed: "holdout_exposed", holdoutExposedAt: "holdout_exposed_at", errorCode: "error_code", errorMessage: "error_message", startedAt: "started_at", completedAt: "completed_at" };
    const values = Object.entries(fields).filter(([key]) => columns[key]); if (!values.length) return current;
    if (fields.status) assertRunTransition(current.status, String(fields.status));
    await sqlite.writer.enqueue(6, "research-run-update", (db) => db.prepare(`UPDATE research_runs SET ${values.map(([key]) => `${columns[key]}=?`).join(",")},updated_at=? WHERE id=?`).run(...values.map(([key, value]) => value instanceof Date ? value.getTime() : typeof value === "boolean" ? Number(value) : ["generationPolicy", "validationPolicy", "deduplicationPolicy", "costModel"].includes(key) ? JSON.stringify(value ?? {}) : value), Date.now(), id));
    return this.get(id);
  },
  async launch(id: string) { return this.update(id, { status: "QUEUED", health: "HEALTHY", stage: "QUEUED", progress: 0, errorCode: null, errorMessage: null }); },
  async claimNext() { return sqlite.writer.enqueue(6, "research-run-claim", (db) => db.transaction(() => { const row = db.prepare("SELECT * FROM research_runs WHERE status IN ('QUEUED','RESUMING') ORDER BY created_at LIMIT 1").get() as Row | undefined; if (!row) return null; const now = Date.now(); db.prepare("UPDATE research_runs SET status='RUNNING',health='HEALTHY',stage='INITIALIZING',started_at=COALESCE(started_at,?),updated_at=? WHERE id=?").run(now, now, row.id); return mapRun({ ...row, status: "RUNNING", health: "HEALTHY", stage: "INITIALIZING", started_at: row.started_at ?? now, updated_at: now }); })()); },
  async requestPause(id: string) { return this.update(id, { status: "PAUSING" }); },
  async requestCancel(id: string) { return this.update(id, { status: "CANCELLING" }); },
  async exposeHoldout(id: string) { const run = this.get(id); if (!run || !run.holdoutEvaluated || run.holdoutExposed) return run; const exposedAt = new Date(); await this.update(id, { holdoutExposed: true, holdoutExposedAt: exposedAt }); await this.log(id, "INFO", "HOLDOUT", "HOLDOUT_EXPOSED", "Holdout results exposed to the user", { exposedAt: exposedAt.toISOString() }); return this.get(id); },
  async recoverInterrupted() { return sqlite.writer.enqueue(6, "research-run-recover", (db) => db.prepare("UPDATE research_runs SET status='QUEUED',stage='QUEUED',error_code='RESTART_RECOVERY',error_message='Recovered after process restart',updated_at=? WHERE status IN ('RUNNING','PAUSING','CANCELLING')").run(Date.now()).changes); },
  async log(id: string, level: string, stage: string, eventType: string, message: string, details?: unknown) { await sqlite.writer.enqueue(7, "research-event", (db) => db.prepare("INSERT INTO research_events(id,research_run_id,timestamp,level,stage,event_type,message,details_json) VALUES(?,?,?,?,?,?,?,?)").run(randomUUID(), id, Date.now(), level, stage, eventType, message, details === undefined ? null : JSON.stringify(details))); },
  events(id: string) { return (sqlite.reader.prepare("SELECT * FROM research_events WHERE research_run_id=? ORDER BY timestamp DESC LIMIT 2000").all(id) as Row[]).map((row) => ({ ...row, details: row.details_json ? json(row.details_json, null) : null, timestamp: date(row.timestamp) })); },
  async insertCandidate(input: { researchRunId: string; generationIndex: number; status: string; family: string; direction: string; rawAst: unknown; normalizedAst: unknown; normalizedHash: string; semanticFingerprint?: string | null; configuration: unknown; complexityScore: number; complexityBreakdown?: unknown; metrics?: unknown; preflightMetrics?: unknown; score?: number | null; paretoRank?: number | null; rejectionStage?: string | null; rejectionReason?: string | null; validationStatus?: string | null; validationErrors?: unknown; generationAttemptIndex?: number | null; duplicateOfCandidateId?: string | null; terminalReason?: string | null; stageRejectionReasons?: unknown; humanDescription?: string | null; generatorVersion?: string | null; grammarVersion?: string | null; registryVersion?: string | null }) {
    const id = randomUUID(), now = Date.now(); try { await sqlite.writer.enqueue(7, "research-candidate-create", (db) => db.prepare("INSERT INTO research_candidates(id,research_run_id,generation_index,status,family,direction,raw_ast_json,normalized_ast_json,normalized_hash,configuration_json,complexity_score,metrics_json,score,pareto_rank,rejection_stage,rejection_reason,created_at,updated_at,semantic_fingerprint,generation_attempt_index,duplicate_of_candidate_id,validation_status,validation_errors_json,preflight_metrics_json,terminal_reason,stage_rejection_reasons_json,complexity_breakdown_json,human_description,generator_version,grammar_version,registry_version) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)").run(id, input.researchRunId, input.generationIndex, input.status, input.family, input.direction, JSON.stringify(input.rawAst), JSON.stringify(input.normalizedAst), input.normalizedHash, JSON.stringify(input.configuration), input.complexityScore, JSON.stringify(input.metrics ?? {}), input.score ?? null, input.paretoRank ?? null, input.rejectionStage ?? null, input.rejectionReason ?? null, now, now, input.semanticFingerprint ?? null, input.generationAttemptIndex ?? null, input.duplicateOfCandidateId ?? null, input.validationStatus ?? null, JSON.stringify(input.validationErrors ?? []), JSON.stringify(input.preflightMetrics ?? {}), input.terminalReason ?? null, JSON.stringify(input.stageRejectionReasons ?? {}), JSON.stringify(input.complexityBreakdown ?? {}), input.humanDescription ?? null, input.generatorVersion ?? null, input.grammarVersion ?? null, input.registryVersion ?? null)); return this.candidate(id)!; } catch (error) { if ((error as { code?: string }).code === "SQLITE_CONSTRAINT_UNIQUE") return null; throw error; } },
  candidate(id: string) { const row = sqlite.reader.prepare("SELECT * FROM research_candidates WHERE id=?").get(id) as Row | undefined; return row ? mapCandidate(row) : null; },
  findByFingerprint(runId: string, fingerprint: string) { const row = sqlite.reader.prepare("SELECT * FROM research_candidates WHERE research_run_id=? AND (normalized_hash=? OR semantic_fingerprint=?) ORDER BY generation_index LIMIT 1").get(runId, fingerprint, fingerprint) as Row | undefined; return row ? mapCandidate(row) : null; },
  async updateCandidate(id: string, fields: Record<string, unknown>) {
    const current = this.candidate(id); if (!current) return null;
    const columns: Record<string, string> = { status: "status", metrics: "metrics_json", preflightMetrics: "preflight_metrics_json", score: "score", paretoRank: "pareto_rank", rejectionStage: "rejection_stage", rejectionReason: "rejection_reason", stageRejectionReasons: "stage_rejection_reasons_json", promotedStrategyId: "promoted_strategy_id", validationStatus: "validation_status", validationErrors: "validation_errors_json", terminalReason: "terminal_reason", humanDescription: "human_description" };
    const values = Object.entries(fields).filter(([key]) => columns[key]); if (!values.length) return current;
    if (fields.status && String(fields.status) !== current.status && current.status !== String(fields.status) && terminalCandidateStatuses.has(current.status)) throw new Error(`Invalid Candidate transition ${current.status} -> ${fields.status}`);
    await sqlite.writer.enqueue(7, "research-candidate-update", (db) => db.prepare(`UPDATE research_candidates SET ${values.map(([key]) => `${columns[key]}=?`).join(",")},updated_at=? WHERE id=?`).run(...values.map(([key, value]) => ["metrics", "preflightMetrics", "stageRejectionReasons", "validationErrors"].includes(key) ? JSON.stringify(value ?? {}) : value), Date.now(), id)); return this.candidate(id);
  },
  candidates(runId: string, limit = 100, offset = 0) { return (sqlite.reader.prepare("SELECT * FROM research_candidates WHERE research_run_id=? ORDER BY score DESC NULLS LAST, generation_index LIMIT ? OFFSET ?").all(runId, limit, offset) as Row[]).map(mapCandidate); },
  candidateCount(runId: string) { return Number((sqlite.reader.prepare("SELECT count(*) count FROM research_candidates WHERE research_run_id=?").get(runId) as { count: number }).count); },
  async reconcile(runId: string) { const row = sqlite.reader.prepare("SELECT count(*) total, sum(status IN ('GENERATED','FINALIST')) transient, sum(status='STRUCTURAL_REJECTED') staticRejected, sum(validation_status='VALID') accepted, sum(validation_status='VALID' AND status NOT IN ('GENERATED','FINALIST')) evaluated FROM research_candidates WHERE research_run_id=?").get(runId) as Row; const counters = { acceptedCandidateCount: Number(row.accepted ?? 0), evaluatedCandidateCount: Number(row.evaluated ?? 0), unevaluatedCandidateCount: Number(row.transient ?? 0), staticRejectedCount: Number(row.staticRejected ?? 0), structurallyRejectedCount: Number(row.staticRejected ?? 0) }; await this.update(runId, counters); return { ...counters, total: Number(row.total ?? 0), transient: Number(row.transient ?? 0) }; },
  async recordPromotion(input: { candidateId: string; runId: string; strategyId: string; strategyVersionId: string; verificationRunId?: string | null; actor?: string | null; note?: string | null }) { const id = randomUUID(), now = Date.now(); await sqlite.writer.enqueue(6, "research-candidate-promotion", (db) => db.transaction(() => { db.prepare("INSERT INTO research_candidate_promotions(id,research_candidate_id,research_run_id,strategy_id,strategy_version_id,verification_run_id,actor,note,created_at) VALUES(?,?,?,?,?,?,?,?,?)").run(id, input.candidateId, input.runId, input.strategyId, input.strategyVersionId, input.verificationRunId ?? null, input.actor ?? null, input.note ?? null, now); db.prepare("UPDATE research_candidates SET status='PROMOTED',promoted_strategy_id=?,terminal_reason='PROMOTED_BY_USER',updated_at=? WHERE id=?").run(input.strategyId, now, input.candidateId); db.prepare("UPDATE research_runs SET promoted_count=promoted_count+1,updated_at=? WHERE id=?").run(now, input.runId); })()); return { id, createdAt: new Date(now) }; },
};
