import { createHash } from "node:crypto";
import { alignCeil, bucketOpen, expectedClose, intervalMs } from "../domain/intervals.js";
import { candleRepository } from "../db/repository.js";
import { metadataRepository } from "../db/repository.js";
import { FeatureEngine } from "./feature-engine.js";
import { METRICS_ENGINE_VERSION, calendarBreakdown, scorecard, verificationMetrics } from "./metrics.js";
import { strategyRepository, verificationRepository } from "./repository.js";
import { simulate } from "./simulation.js";
import type { ExecutionRules } from "./simulation.js";
import { strategyWarmupBars, type StrategyConfig } from "./model.js";
import { MONTE_CARLO_ENGINE_VERSION, monteCarlo } from "./monte-carlo.js";
import { WALK_FORWARD_POLICY_VERSION, selectWalkForwardCandidate } from "./walk-forward.js";
import { auditTradeFees } from "./fee-audit.js";

export const SIMULATION_ENGINE_VERSION = "2026.09.accounting.1";
export const WALK_FORWARD_ENGINE_VERSION = "2026.09.eligible-selection.1";
export const ROBUSTNESS_ENGINE_VERSION = "2026.09.accounting.1";
export const STRESS_ENGINE_VERSION = "2026.09.accounting.1";
export const REPORT_ENGINE_VERSION = "2026.09.accounting.1";
function closedWindow(start: Date, end: Date, timeframe: string) {
  const effectiveStart = alignCeil(start, timeframe);
  const endingBucket = bucketOpen(end, timeframe);
  const effectiveEnd = end.getTime() >= expectedClose(endingBucket, timeframe).getTime()
    ? endingBucket
    : new Date(endingBucket.getTime() - intervalMs(timeframe));
  return { effectiveStart, effectiveEnd };
}
export function historicalAvailability(symbol: string, timeframes: string[], start: Date, end: Date) {
  return timeframes.map((timeframe) => {
    const range = closedWindow(start, end, timeframe);
    if (range.effectiveEnd < range.effectiveStart) return { symbol, timeframe, first: null, last: null, candles: 0, completeCandles: 0, gaps: 0, completeness: 0, effectiveStart: null, effectiveEnd: null };
    const rows = candleRepository.verificationRange(symbol, timeframe, range.effectiveStart, range.effectiveEnd);
    const gaps = candleRepository.missingRanges(symbol, timeframe, range.effectiveStart, range.effectiveEnd, intervalMs(timeframe));
    const expected = Math.floor((range.effectiveEnd.getTime() - range.effectiveStart.getTime()) / intervalMs(timeframe)) + 1;
    return { symbol, timeframe, first: rows[0]?.openTime ?? null, last: rows.at(-1)?.closeTime ?? null, candles: rows.length, completeCandles: rows.length, gaps: gaps.length, completeness: expected ? rows.length / expected * 100 : 0, effectiveStart: rows[0]?.openTime ?? null, effectiveEnd: rows.at(-1)?.closeTime ?? null };
  });
}
export function dataFingerprint(symbol: string, timeframes: string[], start: Date, end: Date, warmupBars: Record<string, number> = {}) { const availability = historicalAvailability(symbol, timeframes, start, end); const warmup = timeframes.map((timeframe) => { const bars = warmupBars[timeframe] ?? 0, contextStart = new Date(start.getTime() - intervalMs(timeframe) * bars), available = bars ? candleRepository.verificationRange(symbol, timeframe, contextStart, new Date(start.getTime() - 1)).length : 0; return { timeframe, bars, contextStart: contextStart.toISOString(), available, complete: available >= bars }; }); const snapshot = { symbol, requestedRange: { start: start.toISOString(), end: end.toISOString() }, frames: availability, warmup }; return { ...snapshot, checksum: createHash("sha256").update(JSON.stringify(snapshot)).digest("hex") }; }
function executionRules(metadata: ReturnType<typeof metadataRepository.get>): ExecutionRules { return metadata ? { tickSize: metadata.tick_size == null ? null : String(metadata.tick_size), stepSize: metadata.step_size == null ? null : String(metadata.step_size), minQty: metadata.min_qty == null ? null : String(metadata.min_qty), minNotional: metadata.min_notional == null ? null : String(metadata.min_notional) } : {}; }
function stressSummary(metrics: ReturnType<typeof verificationMetrics>) { return { trades: metrics.tradeCount, netProfit: metrics.netProfit, netProfitPct: metrics.netProfitPct, profitFactor: metrics.profitFactor, maxDrawdownPct: metrics.maxDrawdownPct, expectancy: metrics.expectancy }; }
function scalePeriods<T>(value: T, multiplier: number): T { if (Array.isArray(value)) return value.map((item) => scalePeriods(item, multiplier)) as T; if (!value || typeof value !== "object") return value; const copy = Object.fromEntries(Object.entries(value as Record<string, unknown>).map(([key, item]) => [key, key === "period" && typeof item === "number" ? Math.max(2, Math.round(item * multiplier)) : scalePeriods(item, multiplier)])); return copy as T; }
function marketRegimes(trades: Array<{ entryTime: number; netPnl: string }>, engine: FeatureEngine, timeframe: string) { const groups: Record<string, { regime: string; trades: number; netProfit: number; wins: number }> = {}; for (const trade of trades) { const asOf = new Date(trade.entryTime), fast = engine.value({ indicator: "ema", parameters: { period: 50 }, timeframe }, asOf), slow = engine.value({ indicator: "ema", parameters: { period: 200 }, timeframe }, asOf); const regime = !Number.isFinite(fast) || !Number.isFinite(slow) ? "REGIME_CLASSIFICATION_UNAVAILABLE" : Math.abs(fast / slow - 1) < .001 ? "TRANSITION" : fast > slow ? "BULL_TREND" : "BEAR_TREND"; const group = groups[regime] ??= { regime, trades: 0, netProfit: 0, wins: 0 }; group.trades++; group.netProfit += Number(trade.netPnl); group.wins += Number(trade.netPnl) > 0 ? 1 : 0; } return Object.values(groups).map((group) => ({ ...group, winRate: group.trades ? group.wins / group.trades * 100 : 0, explanation: group.regime === "REGIME_CLASSIFICATION_UNAVAILABLE" ? "Strategy warm-up was complete; optional regime classifier lacked EMA50/EMA200 history." : undefined })); }

class VerificationWorker {
  private running = false; private timer: NodeJS.Timeout | null = null;
  start() { if (this.timer) return; void verificationRepository.recoverInterrupted().then(() => this.runOnce()); this.timer = setInterval(() => void this.runOnce(), 500); }
  stop() { if (this.timer) clearInterval(this.timer); this.timer = null; }
  async runOnce() { if (this.running) return; const run = await verificationRepository.claimNext(); if (!run) return; this.running = true; try { await this.execute(run); } catch (error) { await verificationRepository.update(run.id, { status: "FAILED", stage: "FAILED", errorCode: "VERIFICATION_FAILED", errorMessage: error instanceof Error ? error.message : "Unknown verification error", completedAt: new Date() }); await verificationRepository.log(run.id, "ERROR", "FAILED", "RUN_FAILED", error instanceof Error ? error.message : "Unknown verification error"); } finally { this.running = false; } }
  private async execute(run: ReturnType<typeof verificationRepository.get> extends infer T ? Exclude<T, null> : never) {
    const version = strategyRepository.version(run.strategyVersionId); if (!version) throw new Error("Strategy version was not found"); const config = version.configuration;
    const warmupBars = strategyWarmupBars(config), warmupStart = new Date(Math.min(...Object.entries(warmupBars).map(([timeframe, bars]) => run.requestedStart.getTime() - intervalMs(timeframe) * bars)));
    await verificationRepository.log(run.id, "INFO", "LOADING_DATA", "RUN_STARTED", `Verification started for ${run.symbol}`); const engine = new FeatureEngine(run.symbol, warmupStart, run.requestedEnd).load(config.requiredTimeframes); const strategyWarmupComplete = Object.values((run.dataFingerprint as Record<string, unknown>).warmup ?? {}).every((item) => (item as Record<string, unknown>).complete !== false); if (!strategyWarmupComplete) throw new Error("STRATEGY_WARMUP_INCOMPLETE: required indicator context is unavailable"); const triggerCount = engine.candles(config.triggerTimeframe).filter((c) => c.closeTime >= run.requestedStart && c.closeTime <= run.requestedEnd).length; if (!triggerCount) throw new Error(`No complete ${config.triggerTimeframe} candles in selected range`);
    const metadata = metadataRepository.get(run.symbol), rules = executionRules(metadata); if (!metadata) await verificationRepository.log(run.id, "WARN", "LOADING_DATA", "EXCHANGE_RULES_MISSING", "Exchange metadata was unavailable; execution rules were not rounded."); const triggerCandles = engine.candles(config.triggerTimeframe).filter((c) => c.closeTime >= run.requestedStart && c.closeTime <= run.requestedEnd); await verificationRepository.update(run.id, { stage: "SIMULATING", progress: .1, stageProgress: 0, actualStart: triggerCandles[0].openTime, actualEnd: triggerCandles.at(-1)!.closeTime }); const baseWindow = { start: run.requestedStart, end: run.requestedEnd }; const simulated = await simulate(config, engine, Number(run.options.initialBalance), (processed, trades) => { if (processed % 500 === 0) void verificationRepository.update(run.id, { candlesProcessed: processed, eventsProcessed: processed, tradesSimulated: trades, stageProgress: processed / triggerCount, progress: .1 + .55 * processed / triggerCount }); }, () => verificationRepository.get(run.id)?.cancelRequested ?? false, rules, baseWindow);
    if (simulated.cancelled || verificationRepository.get(run.id)?.cancelRequested) { await verificationRepository.update(run.id, { status: "CANCELLED", stage: "CANCELLED", completedAt: new Date(), candlesProcessed: simulated.funnel.triggerEvents, tradesSimulated: simulated.trades.length }); await verificationRepository.log(run.id, "INFO", "CANCELLED", "RUN_CANCELLED", "Run cancelled safely at a checkpoint"); return; }
    await verificationRepository.update(run.id, { stage: "METRICS", progress: .7, stageProgress: 0 }); const initial = Number(run.options.initialBalance); const baseMetrics = verificationMetrics(simulated.trades, simulated.equity), feeAudit = auditTradeFees(simulated.trades, config.costs); const metrics = { ...baseMetrics, feeAudit: { ...feeAudit, feesPctInitialBalance: initial ? feeAudit.totalFees / initial * 100 : null, feesPctGrossTradingPnl: baseMetrics.grossPnl ? feeAudit.totalFees / Math.abs(baseMetrics.grossPnl) * 100 : null } }; const oosTime = run.requestedStart.getTime() + (run.requestedEnd.getTime() - run.requestedStart.getTime()) * Number(run.options.oosSplit), oosStart = new Date(oosTime); const oosSimulation = await simulate(config, engine, initial, undefined, () => verificationRepository.get(run.id)?.cancelRequested ?? false, rules, { start: oosStart, end: run.requestedEnd }); if (oosSimulation.cancelled) { await verificationRepository.update(run.id, { status: "CANCELLED", stage: "CANCELLED", completedAt: new Date() }); return; } const oosMetrics = verificationMetrics(oosSimulation.trades, oosSimulation.equity); const monteCarloCount = run.profile === "QUICK" ? 0 : Number(run.options.monteCarloCount); const mc = monteCarloCount ? monteCarlo(simulated.trades, initial, monteCarloCount, run.randomSeed, config) : null;
    let costStress: Array<Record<string, unknown>> | null = null;
    if (run.profile !== "QUICK") { await verificationRepository.update(run.id, { stage: "COST_STRESS", progress: .78, stageProgress: 0 }); const scenarios = [{ name: "DOUBLE_FRICTION", takerFeePct: config.costs.takerFeePct * 2, slippageBps: config.costs.slippageBps * 2 }, { name: "SEVERE_FRICTION", takerFeePct: Math.max(config.costs.takerFeePct * 3, .12), slippageBps: Math.max(config.costs.slippageBps * 4, 8) }]; costStress = []; for (let index = 0; index < scenarios.length; index++) { const scenario = scenarios[index], stressed = await simulate({ ...config, costs: { ...config.costs, takerFeePct: scenario.takerFeePct, slippageBps: scenario.slippageBps } }, engine, initial, undefined, () => verificationRepository.get(run.id)?.cancelRequested ?? false, rules, baseWindow); if (stressed.cancelled) { await verificationRepository.update(run.id, { status: "CANCELLED", stage: "CANCELLED", completedAt: new Date() }); return; } costStress.push({ name: scenario.name, takerFeePct: scenario.takerFeePct, slippageBps: scenario.slippageBps, ...stressSummary(verificationMetrics(stressed.trades, stressed.equity)) }); await verificationRepository.update(run.id, { stageProgress: (index + 1) / scenarios.length, progress: .78 + .12 * (index + 1) / scenarios.length }); } }
    let parameterRobustness: Array<Record<string, unknown>> | null = null;
    if (run.profile === "FULL") { await verificationRepository.update(run.id, { stage: "PARAMETER_ROBUSTNESS", progress: .91, stageProgress: 0 }); parameterRobustness = [{ periodMultiplier: 1, name: "BASELINE", ...stressSummary(metrics) }]; const multipliers = [.8, 1.2]; for (let index = 0; index < multipliers.length; index++) { const multiplier = multipliers[index], robust = await simulate(scalePeriods<StrategyConfig>(config, multiplier), engine, initial, undefined, () => verificationRepository.get(run.id)?.cancelRequested ?? false, rules, baseWindow); if (robust.cancelled) { await verificationRepository.update(run.id, { status: "CANCELLED", stage: "CANCELLED", completedAt: new Date() }); return; } parameterRobustness.push({ periodMultiplier: multiplier, name: `PERIODS_${Math.round(multiplier * 100)}PCT`, ...stressSummary(verificationMetrics(robust.trades, robust.equity)) }); await verificationRepository.update(run.id, { stageProgress: (index + 1) / multipliers.length, progress: .91 + .07 * (index + 1) / multipliers.length }); } }
    let walkForward: Array<Record<string, unknown>> | null = null;
    if (run.profile === "FULL") {
      await verificationRepository.update(run.id, { stage: "WALK_FORWARD", progress: .98, stageProgress: 0 });
      walkForward = [];
      const firstTestAt = run.requestedStart.getTime() + (run.requestedEnd.getTime() - run.requestedStart.getTime()) / 2;
      const testWidth = (run.requestedEnd.getTime() - firstTestAt) / 3;
      const multipliers = [.8, 1, 1.2];
      for (let fold = 0; fold < 3; fold++) {
        const testStart = new Date(firstTestAt + fold * testWidth);
        const testEnd = new Date(fold === 2 ? run.requestedEnd.getTime() : firstTestAt + (fold + 1) * testWidth);
        const trainingEnd = new Date(testStart.getTime() - 1);
        const trainingCandidates: Array<{ periodMultiplier: number; metrics: ReturnType<typeof verificationMetrics> }> = [];
        for (const periodMultiplier of multipliers) {
          const trained = await simulate(scalePeriods<StrategyConfig>(config, periodMultiplier), engine, initial, undefined, () => verificationRepository.get(run.id)?.cancelRequested ?? false, rules, { start: run.requestedStart, end: trainingEnd });
          if (trained.cancelled) { await verificationRepository.update(run.id, { status: "CANCELLED", stage: "CANCELLED", completedAt: new Date() }); return; }
          trainingCandidates.push({ periodMultiplier, metrics: verificationMetrics(trained.trades, trained.equity) });
        }
        const selection = selectWalkForwardCandidate(trainingCandidates);
        const selectedCandidate = selection.selected ? selection.selected.periodMultiplier : null, base = { fold: fold + 1, policyVersion: WALK_FORWARD_POLICY_VERSION, eligibilityPolicy: selection.policy, trainingPeriod: `${run.requestedStart.toISOString()} → ${trainingEnd.toISOString()}`, testPeriod: `${testStart.toISOString()} → ${testEnd.toISOString()}`, trainStart: run.requestedStart.toISOString(), trainEnd: trainingEnd.toISOString(), testStart: testStart.toISOString(), testEnd: testEnd.toISOString(), totalCandidates: selection.candidates.length, eligibleCandidates: selection.candidates.filter((candidate) => candidate.eligibility.eligible).length, selectedCandidate, selectedParameters: selection.selected ? { periodMultiplier: selection.selected.periodMultiplier } : null, candidates: selection.candidates.map((candidate) => ({ periodMultiplier: candidate.periodMultiplier, ...stressSummary(candidate.metrics), eligibility: candidate.eligibility })) };
        if (!selection.selected) {
          walkForward.push({ ...base, status: "NO_ELIGIBLE_CANDIDATE", selectedPeriodMultiplier: null, trainingTrades: null, trainingNetProfit: null, trainingProfitFactor: null, trainingDrawdown: null, oosTrades: null, oosNetProfit: null, oosProfitFactor: null, rejectionReason: "No candidate satisfied the minimum training eligibility criteria.", outOfSample: null });
          await verificationRepository.update(run.id, { stageProgress: (fold + 1) / 3, progress: .98 + .015 * (fold + 1) / 3 });
          continue;
        }
        const tested = await simulate(scalePeriods<StrategyConfig>(config, selection.selected.periodMultiplier), engine, initial, undefined, () => verificationRepository.get(run.id)?.cancelRequested ?? false, rules, { start: testStart, end: testEnd });
        if (tested.cancelled) { await verificationRepository.update(run.id, { status: "CANCELLED", stage: "CANCELLED", completedAt: new Date() }); return; }
        const outOfSample = stressSummary(verificationMetrics(tested.trades, tested.equity));
        walkForward.push({ ...base, status: "COMPLETED", selectedPeriodMultiplier: selection.selected.periodMultiplier, trainingTrades: selection.selected.metrics.tradeCount, trainingNetProfit: selection.selected.metrics.netProfit, trainingProfitFactor: selection.selected.metrics.profitFactor, trainingDrawdown: selection.selected.metrics.maxDrawdownPct, oosTrades: outOfSample.trades, oosNetProfit: outOfSample.netProfit, oosProfitFactor: outOfSample.profitFactor, rejectionReason: null, ...outOfSample, outOfSample });
        await verificationRepository.update(run.id, { stageProgress: (fold + 1) / 3, progress: .98 + .015 * (fold + 1) / 3 });
      }
    }
    const marketRegimeBreakdown = marketRegimes(simulated.trades, engine, config.triggerTimeframe), breakdownWarmupComplete = !marketRegimeBreakdown.some((row) => row.regime === "REGIME_CLASSIFICATION_UNAVAILABLE");
    const dataAudit = { usesClosedCompleteCandlesOnly: true, pointInTimeFeatureAccess: true, requiredTimeframes: config.requiredTimeframes, triggerTimeframe: config.triggerTimeframe, executionTimeframe: config.executionTimeframe, warmupBars, warmupContextStart: warmupStart.toISOString(), fingerprint: run.dataFingerprint, strategyWarmupComplete, breakdownWarmupComplete, checks: { STRATEGY_WARMUP_COMPLETE: strategyWarmupComplete ? "PASS" : "FAIL", BREAKDOWN_WARMUP_COMPLETE: breakdownWarmupComplete ? "PASS" : "WARNING" }, exchangeRulesApplied: Boolean(metadata), fundingMode: config.costs.fundingMode, knownLimitations: [...(config.costs.fundingMode === "NONE" ? ["Funding was not modeled."] : []), ...(breakdownWarmupComplete ? [] : ["Optional regime classification was unavailable for some trades; this does not invalidate strategy warm-up."])] };
    const walkForwardSummary = Array.isArray(walkForward) ? { totalFolds: walkForward.length, completedFolds: walkForward.filter((fold) => fold.status === "COMPLETED").length, noEligibleCandidateFolds: walkForward.filter((fold) => fold.status === "NO_ELIGIBLE_CANDIDATE").length, insufficientDataFolds: walkForward.filter((fold) => fold.status === "INSUFFICIENT_DATA").length, failedFolds: walkForward.filter((fold) => fold.status === "FAILED").length, foldsWithOosExecuted: walkForward.filter((fold) => fold.status === "COMPLETED" && Number(fold.oosTrades) > 0).length, totalOosTrades: walkForward.reduce((sum, fold) => sum + Number(fold.oosTrades ?? 0), 0) } : null;
    const sc = scorecard(metrics, simulated.warnings); const breakdowns = { calendar: calendarBreakdown(simulated.trades), marketRegimes: marketRegimeBreakdown, outOfSample: { split: Number(run.options.oosSplit), start: oosStart.toISOString(), end: run.requestedEnd.toISOString(), ...stressSummary(oosMetrics) }, monteCarlo: mc, costStress, parameterRobustness, walkForward, walkForwardSummary, dataAudit };
    await verificationRepository.storeTrades(run.id, simulated.trades); await verificationRepository.storeResult(run.id, { metrics, equityCurve: simulated.equity, breakdowns, scorecard: sc, funnel: simulated.funnel, warnings: simulated.warnings }); await verificationRepository.update(run.id, { status: "COMPLETED", stage: "COMPLETED", progress: 1, stageProgress: 1, candlesProcessed: triggerCount, eventsProcessed: triggerCount, tradesSimulated: simulated.trades.length, completedWork: triggerCount, completedAt: new Date() }); await verificationRepository.log(run.id, "INFO", "COMPLETED", "RUN_COMPLETED", `Completed with ${simulated.trades.length} simulated trades`); await (async () => { await import("../db/database.js").then(({ sqlite }) => sqlite.writer.enqueue(5, "strategy-version-status", (db) => db.prepare("UPDATE strategy_versions SET verification_status=? WHERE id=?").run(sc.status === "PASS" ? "VERIFIED" : sc.status === "WARNING" ? "VERIFICATION_WARNING" : "VERIFICATION_FAILED", version.id))); })();
  }
}
export const verificationWorker = new VerificationWorker();
