import { Counter, Gauge, Histogram, Registry, collectDefaultMetrics } from "prom-client";
export const metrics = new Registry(); collectDefaultMetrics({ register: metrics, prefix: "traidin_" });
export const wsMessages = new Counter({ name: "traidin_ws_messages_total", help: "WebSocket messages", registers: [metrics] });
export const closedCandles = new Counter({ name: "traidin_closed_candles_total", help: "Closed candles", registers: [metrics] });
export const persistedCandles = new Counter({ name: "traidin_persisted_candles_total", help: "Persisted candles", registers: [metrics] });
export const reconnects = new Counter({ name: "traidin_ws_reconnections_total", help: "WebSocket reconnections", registers: [metrics] });
export const restErrors = new Counter({ name: "traidin_rest_errors_total", help: "REST errors", registers: [metrics] });
export const activeGaps = new Gauge({ name: "traidin_active_gaps", help: "Active gaps", registers: [metrics] });
export const ingestLatency = new Histogram({ name: "traidin_ingest_latency_ms", help: "Exchange-to-local latency", buckets: [10, 25, 50, 100, 250, 500, 1000, 2500], registers: [metrics] });
export const persistLatency = new Histogram({ name: "traidin_persist_latency_ms", help: "Receive-to-persist latency", buckets: [1, 5, 10, 25, 50, 100, 250, 500], registers: [metrics] });
