import { existsSync, mkdirSync } from "node:fs";
import { basename, isAbsolute, resolve } from "node:path";
import { config } from "../config.js";
import { sqlite } from "./database.js";

const backupDir = isAbsolute(config.SQLITE_BACKUP_DIR) ? config.SQLITE_BACKUP_DIR : resolve(process.cwd(), config.SQLITE_BACKUP_DIR);
const quoteSql = (value: string) => `'${value.replaceAll("'", "''")}'`;
export async function checkpoint(mode: "PASSIVE" | "FULL" | "RESTART" | "TRUNCATE" = "PASSIVE") { return sqlite.writer.enqueue(3, "wal-checkpoint", (db) => db.pragma(`wal_checkpoint(${mode})`)); }
export async function optimize() { return sqlite.writer.enqueue(6, "optimize", (db) => { db.pragma("optimize"); db.prepare("INSERT INTO system_state(key,value_json,updated_at) VALUES('last_optimize',?,?) ON CONFLICT(key) DO UPDATE SET value_json=excluded.value_json,updated_at=excluded.updated_at").run(JSON.stringify({ ok: true }), Date.now()); return { ok: true }; }); }
export async function backup() { mkdirSync(backupDir, { recursive: true }); const stamp = new Date().toISOString().replaceAll(":", "-").replaceAll(".", "-"); const destination = resolve(backupDir, `traidin-${stamp}.db`); if (existsSync(destination)) throw new Error("Backup destination already exists"); await sqlite.writer.enqueue(3, "backup", (db) => { db.exec(`VACUUM INTO ${quoteSql(destination)}`); db.prepare("INSERT INTO system_state(key,value_json,updated_at) VALUES('last_backup',?,?) ON CONFLICT(key) DO UPDATE SET value_json=excluded.value_json,updated_at=excluded.updated_at").run(JSON.stringify({ file: basename(destination) }), Date.now()); }); return { file: basename(destination), directory: basename(backupDir), createdAt: new Date().toISOString() }; }
export async function pruneEvents(days = config.EVENT_RETENTION_DAYS) { const cutoff = Date.now() - days * 86_400_000; return sqlite.writer.enqueue(7, "event-retention", (db) => db.prepare("DELETE FROM system_events WHERE timestamp < ? AND level IN ('DEBUG','INFO','DATA','DB','AGG')").run(cutoff).changes); }
export function databaseOverview() { const raw = sqlite.stats(); const counts = Object.fromEntries(["candles", "system_events", "backfill_jobs", "gaps", "symbol_metadata"].map((table) => [table, Number((sqlite.reader.prepare(`SELECT count(*) AS count FROM ${table}`).get() as { count: number }).count)])); const last = sqlite.reader.prepare("SELECT max(persisted_at) AS last_write FROM candles").get() as { last_write: number | null }; return { ...raw, path: `.../${basename(sqlite.path)}`, counts, lastCandleWriteAt: last.last_write ? new Date(last.last_write).toISOString() : null }; }
