import { afterAll, beforeAll, describe, expect, it } from "vitest";
import { mkdtempSync, rmSync } from "node:fs";
import { join } from "node:path";
import { tmpdir } from "node:os";
import { candle } from "./fixtures.js";
import { aggregateCandles } from "../domain/aggregate.js";

const directory = mkdtempSync(join(tmpdir(), "traidin-sqlite-")); let database: typeof import("../db/database.js"); let repository: typeof import("../db/repository.js"); let maintenance: typeof import("../db/maintenance.js"); let aggregation: typeof import("../workers/aggregation.js");
beforeAll(async () => { process.env.DATABASE_URL = `sqlite:${join(directory, "test.db")}`; process.env.SQLITE_BACKUP_DIR = join(directory, "backups"); process.env.START_WORKERS = "false"; database = await import("../db/database.js"); repository = await import("../db/repository.js"); maintenance = await import("../db/maintenance.js"); aggregation = await import("../workers/aggregation.js"); });
afterAll(() => { database.sqlite.close(); rmSync(directory, { recursive: true, force: true }); });
describe("SQLite storage", () => {
  it("enables WAL and required pragmas", () => { const stats = database.sqlite.stats(); expect(stats).toMatchObject({ journalMode: "wal", busyTimeout: 5000, integrity: "ok" }); });
  it("bulk upserts idempotently and keeps decimal text exact", async () => { const start = Date.UTC(2026,0,1); const batch = Array.from({ length: 1000 }, (_, i) => candle(start + i * 60_000)); await repository.candleRepository.upsertMany(batch); await repository.candleRepository.upsertMany(batch.map((c) => ({ ...c, close: "101.300000000000000001" }))); expect(repository.candleRepository.count("BTCUSDT", "1m", new Date(start), new Date(start + 999 * 60_000))).toBe(1000); expect(repository.candleRepository.latest("BTCUSDT")?.close).toBe("101.300000000000000001"); });
  it("detects exact missing ranges", () => { const start = Date.UTC(2026,0,1); database.sqlite.writerConnection.prepare("DELETE FROM candles WHERE open_time IN (?,?)").run(start + 20 * 60_000, start + 21 * 60_000); const gaps = repository.candleRepository.missingRanges("BTCUSDT", "1m", new Date(start), new Date(start + 30 * 60_000), 60_000); expect(gaps[0]).toMatchObject({ count: 2 }); });
  it("reconciles stale incomplete aggregates after base minutes arrive", async () => { const start = Date.UTC(2027,0,1); const minutes = Array.from({ length: 5 }, (_, i) => candle(start + i * 60_000)); const incomplete = aggregateCandles(minutes.slice(0, 4), "5m").candle; await repository.candleRepository.upsertMany(minutes.slice(0, 4)); await repository.candleRepository.upsertMany([incomplete]); expect(repository.candleRepository.incompleteAggregates()).toHaveLength(1); await repository.candleRepository.upsertMany([minutes[4]]); expect(await aggregation.aggregationEngine.reconcileIncomplete()).toBe(1); expect(repository.candleRepository.range("BTCUSDT", "5m", new Date(start), new Date(start), 1)[0]).toMatchObject({ isComplete: true, openTime: new Date(start) }); });
  it("persists job checkpoints and recalculates the final estimate", async () => { const job = await repository.jobRepository.create({ symbol: "BTCUSDT", timeframe: "1m", startTime: new Date(0), untilNow: true, estimatedCandles: 10 }); await repository.jobRepository.update(job.id, { status: "RUNNING", checkpointTime: new Date(60_000), persistedCandles: 2 }); await repository.jobRepository.recoverInterrupted(); expect(repository.jobRepository.get(job.id)).toMatchObject({ status: "PENDING", persistedCandles: 2 }); await repository.jobRepository.update(job.id, { status: "COMPLETED", estimatedCandles: 2 }); expect(repository.jobRepository.get(job.id)).toMatchObject({ status: "COMPLETED", estimatedCandles: 2 }); });
  it("prioritizes live writes ahead of queued historical work", async () => { const order: number[] = []; const first = database.sqlite.writer.enqueue(5, "first", () => order.push(5)); const low = database.sqlite.writer.enqueue(6, "low", () => order.push(6)); const live = database.sqlite.writer.enqueue(1, "live", () => order.push(1)); await Promise.all([first, low, live]); expect(order).toEqual([1,5,6]); });
  it("checkpoints, optimizes and creates a safe backup", async () => { await maintenance.checkpoint("PASSIVE"); await maintenance.optimize(); const result = await maintenance.backup(); expect(result.file).toMatch(/^traidin-.+\.db$/); });
  it("applies versioned migrations and rejects invalid gap ranges", () => { expect(database.sqlite.reader.prepare("SELECT max(version) AS version FROM schema_migrations").get()).toMatchObject({ version: 2 }); expect(() => database.sqlite.writerConnection.prepare("INSERT INTO gaps(id,symbol,timeframe,gap_start,gap_end,expected_candles,status,detected_at) VALUES('invalid','BTCUSDT','1m',2,1,0,'DETECTED',0)").run()).toThrow(/invalid gap range/); });
  it("persists non-secret runtime settings", async () => { const value = { symbols: ["BTCUSDT"], aggregatedTimeframes: ["5m"], eventRetentionDays: 7, streamsEnabled: false }; await repository.systemStateRepository.set("test-settings", value); expect(repository.systemStateRepository.get("test-settings")).toEqual(value); });
});
